### ISSUE TITLE
Strange behaviour with `Elem`

### ISSUE THREAD

**Issue by mpickering** [goldfirere/singletons#106]
Using the promoted type family `Elem` produces some unexpected results.

```
*Hive> let (p :: Proxy (Elem Bool '[Bool])) = Proxy
*Hive> let (p1 :: Proxy 'True) = p

<interactive>:47:27:
    Couldn't match type ‘(Bool Data.Singletons.Prelude.Eq.:== Bool)
                         Data.Singletons.Prelude.Bool.:|| singletons-1.0:Data.Singletons.Prelude.Instances.FalseSym0’
                  with ‘'True’
    Expected type: Proxy 'True
      Actual type: Proxy (Elem Bool '[Bool])
    In the expression: p
    In a pattern binding: (p1 :: Proxy 'True) = p
```

OTOH, using a type literal is fine.

```
*Hive> let (p :: Proxy (Elem "5" '["5"])) = Proxy
*Hive> let (p1 :: Proxy 'True) = p
```

Defining the type family by hand works as expected.

```
type family MyElem (a :: k) (b :: [k]) :: Bool where
    MyElem a '[] = False
    MyElem a (a ': xs) = True
    MyElem a (b ': xs) = MyElem a xs

*Hive> let (p :: Proxy (MyElem Bool '[Bool])) = Proxy
*Hive> let (p1 :: Proxy 'True) = p
```

**Comment by goldfirere** [comment]
This is correct behavior.

The problem is that there is not a good, canonical definition of `:==` over the kind `*`. See https://github.com/ghc/ghc/blob/master/libraries/base/Data/Type/Equality.hs#L131 for discussion. Because there are no instances for `:==` over `*` by default, `Elem` can't make progress. If you import `Data.Singletons.TypeRepStar`, your initial example should work. Or, import `Data.Singletons.CustomStar` and call `singletonStar` appropriately; that should work too.

The reason your `MyElem` works is that it uses non-linear patterns (that is, a repeated variable on the left-hand side) instead of `:==` internally.

For better or worse, custom-written type families can exploit capabilities available in the type family language (such as repeated variables) that are not available in the term function language. My (somewhat sad) experience is that power use of type families works better with custom-written ones instead of the singletons-generated ones. The singletons-generated ones aren't wrong, exactly, but they're just not as fine-tuned as hand-written ones can be.

I'm closing this ticket, but if you have a concrete suggestion of how to improve documentation here, please post and reopen. Thanks!
