### ISSUE TITLE
singletonsOnly needs better documentation

### ISSUE THREAD

**Issue by andrewthad** [goldfirere/singletons#109]
When I run
    $(singletonsOnly [d| data Brother = Drew | Luke | Jake | Josh |])

I get this:

    intro.lhs:53:5:
    The exact Name ‘Brother_aepi’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU), 
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful

    intro.lhs:53:5:
    The exact Name ‘Josh_aepj’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU), 
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful

    intro.lhs:53:5:
    The exact Name ‘Jake_aepk’ is not in scope
      Probable cause: you used a unique Template Haskell name (NameU), 
      perhaps via newName, but did not bind it
      If that's it, then -ddump-splices might be useful

     ... etc.

**Comment by andrewthad** [comment]
Minimal case to reproduce:

    {-# LANGUAGE DataKinds, PolyKinds, TypeOperators, TypeFamilies #-}
    {-# LANGUAGE FlexibleContexts, FlexibleInstances, NoMonomorphismRestriction #-}
    {-# LANGUAGE GADTs, TypeSynonymInstances, TemplateHaskell, StandaloneDeriving, ScopedTypeVariables #-}
    import Data.Char
    import Data.Singletons.TH

    $(singletonsOnly [d| data Brother = Drew | Luke | Jake | Josh |])

    main :: IO ()
    main = putStrLn "Everything good"

**Comment by goldfirere** [comment]
That's expected behavior. The "only" bit of `singletonsOnly` means that the TH splice does not emit the original, term-level definition when it is processed. So, there are no constructors `Drew`, `Luke`, etc.

Use `singletons` instead.

But, it occurs to me that no datatype defined within `singletonsOnly` will work. I will leave this issue open as a reminder to update the documentation.

If you already have a datatype for which you want singletons, use `genSingletons`.

**Comment by andrewthad** [comment]
Thank you for the clarification. That does make sense.
