### ISSUE TITLE
Singletons without S prefix

### ISSUE THREAD

**Issue by andrewthad** [goldfirere/singletons#115]
When I make a type

    data Color = Red | Green | Blue

and then call `genSingletons`, I get nice singletons like `SGreen :: Sing Green`. It would be nice to be able have it named `Green` instead of `SGreen` though. I realize that there's still a data constructor named `Green` in scope, so there would be some ambiguity. I could always import `SGreen` into another module, rename it to `Green`, and export there, but that seems like a huge workaround to get this what I want. Is there a way to do something like this in the singletons package? Just to clarify, I don't care about the `Green` data constructor. I don't even want it. I want to have `Green` to refer (on the value level) to the singleton and (on the type level) to a type of kind `Color`. Thanks.

As an addendum, my reason are largely motivated by style. I find prefixing everything with `S` to be unsightly.

**Comment by goldfirere** [comment]
Yes, the `S`s are incredibly annoying. But I don't see a good way to do what you want. It could work only with `genSingletons`, because that function can be called on an already-defined type in another module. Plain old `singletons` is required to use a new name to avoid a clash (it's not just an ambiguity problem). Then there's the fact that the whole singetonization scheme relies quite heavily on having a deterministic way to get from an original name to a singletonized name.

Could these problems be circumvented by various tomfoolery? Yes, I believe so. But I'm afraid I don't think it's worth it. I could consider adding support for, say, a quasiquoter (named `s` of course) that puts the `S`s on for you, but does no other processing. So, `[s| a + Succ b |]` would become `sA %:+ SSucc sB`. Would that accommodate your need?

**Comment by andrewthad** [comment]
The quasiquoter to add the S's is an interesting idea, but I personally find that using quasiquotation everywhere is even more unsightly than prefixing with the S's. I'll pitch one other approach to solving this issue, and if it doesn't seem good to you, then I'll spend some more time thinking about this. I'm not familiar with template haskell, but if there was a function similar to `genSingletons` but that worked like this instead:

Data type defined here:

    module Foo where
    data Color = Red | Green | Blue

Current way that `genSingletons` is used:

    module G1 where
    import Foo
    genSingletons [ ''Color ] -- creates SGreen, SRed, SBlue

Hypothetical Function `genSingletonsFrom`
    module G2 where
    import qualified Foo as F
    genSingletonsFrom [ ''F, ''Color]  -- creates Green, Red, Blue

I don't know is the TH syntax is right, but I hope that this communicates the idea. If I understand correctly, `genSingletonsFrom` should be able to create singletons with the original names. But I may be wrong, or this might be a pain to do.

**Comment by andrewthad** [comment]
I figured out how to do this. Here is an example:

    module SingGate where
    import Data.Singletons

    -- The prefix C stands for constructor.
    data Brother = CDrew | CLuke | CJake                                 

    data instance Sing 'CDrew = Drew
    data instance Sing 'CLuke = Luke                                     
    data instance Sing 'CJake = Jake                                     
    type Drew = 'CDrew                                                   
    type Luke = 'CLuke                                                   
    type Jake = 'CJake

It would be nice if we had a quasiquoter that we could call like `genSingletonsOther [''Brother]` that would strip the prefixed `C` from each data constructor and build what's in the rest of the example code snippet. Then we have singletons that match the type names and everything is exported correctly.

**Comment by goldfirere** [comment]
I'm afraid your solution will end up falling short. Consider this alternative:

```
data instance Sing (x :: Brother) where
  Drew :: Sing 'CDrew
  Luke :: Sing 'CLuke
  Jake :: Sing 'CJake
```

This will behave differently than your encoding in a key way: when pattern-matching `x :: Sing (b :: Brother)` against, say, `Drew`, your encoding requires knowing that `b ~ 'CDrew`. My encoding does not require knowing this in advance, but instead provides the equality `b ~ 'CDrew` in the body of the pattern-match.

Additionally, the `genSingletonsOther` works quite poorly with the rest of the *singletons* infrastructure. A pervasive assumption is that we can get from an original definition to a singletonized one simply by looking at the original name. If presented with `CDrew`, do we go to `SCDrew` or `Drew`? It's ambiguous, and this would be very hard engineer around.

So, using type synonyms (and pattern synonyms for data constructors) can help, but I'm currently against putting this feature into the library directly. If you wish to convince me otherwise, round up compatriots who also want this feature, and specify it precisely. Or, it shouldn't be hard to put the Template Haskell code into its own package -- you're just generating synonym definitions, and it's all quite apart from the *singletons* internals.

I *am* sympathetic to the ugliness of all the `S`s, but I don't see an easy solution here.

**Comment by andrewthad** [comment]
I can definitely agree with your concern about it not really fitting in with the rest of the singletons infrastructure. And I do feel that I'm trying to do something that is a little bit orthogonal to the goals of the singletons package. This probably does make sense for me to put in a separate package. Thanks for entertaining my thoughts today.

**Comment by goldfirere** [comment]
OK -- closing the ticket then.

**Comment by gibiansky** [comment]
@goldfirere Is there an option to move the prefix to the type level rather than the term level? That is, the singletons would be `Green`, `Red`, etc, and the type-level would be, say, `LGreen`, `LRed`, etc? (`L` for lifted?)

**Comment by goldfirere** [comment]
No such option currently exists. And it would be very hard to add, because the library depends on having a function of type `String -> String` that goes from an unrefined name to a singleton name. Your proposal would require adding more information to definitions to make this conversion. I suppose it's all possible, but it's a major change.

I'd be more sympathetic to changing the whole thing to require the new syntax -- which is better in some ways -- but this would be entirely backward incompatible.

**Comment by gibiansky** [comment]
I may be misunderstanding, but why does that make it hard to add? One could define such a function via
```haskell
unrefinedToSingleton :: String -> String
unrefinedToSingleton = drop 1
```
The thing that one would have to add is a few configuration options:

1. How to go from unrefined to singleton
2. How to go from source-level to unrefined

Then after parsing you would apply the source-level to unrefined transformation (adding the `L`) and then the configurable unrefined to singleton would work as it normally does. 

This seems like a fairly straightforward refactoring from the outside. Is there a significant reason that this can't be done or would be harder than it sounds? If not, would you accept such a change as a PR?  (It would be completely backwards compatible, since the default options could just keep the current functionality.)

**Comment by goldfirere** [comment]
Your `unrefinedToSingleton` works, yes, but only with the configuration you've described. That is, the function would not work with the default configuration. So this means adding a parameter to the function indicating the configuration. This isn't terrible. But what if different singletons use different configurations? Then there would have to be some lookup mechanism to learn which configuration is used for each type. This mechanism, in turn, would probably have to work with `ANN` pragmas. Again, not totally terrible, but the power-to-weight here is wrong, in my opinion. The other option here is to allow only one configuration in a program, but then that requires a bifurcation of the landscape that uses singletons.

If I'm wrong here, I'm happy to consider a PR, but perhaps it makes sense for me to see an early draft before too much time is sunk in.

**Comment by gibiansky** [comment]
In IHaskell we are actually looking into using pattern synonyms and curated exports to have the same effect. We'll see how that goes - that might end up being an easy solution, albeit limited to new ghc.

**Comment by goldfirere** [comment]
"the same effect" -- what do you mean here?

And, out of curiosity, what are you using singletons for?

**Comment by gibiansky** [comment]
The same effect meaning allowing us to write constructors without the `S`.

For example, we roughly have the following:
```
-- can't change this because singletons generates it
data WithS = SField1 | SField2 | SField3
```
but we can add
```
pattern Field1 = SField1
pattern Field2 = SField2
pattern Field3 = SField3
```

This poses some challenges but perhaps we can use this mechanism to provide convenient naming without the `S`. I'm not exactly sure whether it's possible, and I don't know how pattern synonyms are treated at the type level and whether there will be some sort of collisions; perhaps we can also fiddle with our original names to avoid this. We'll see if we can perhaps hide some of the `singletons`-based implementation details using a large number of hand crafted pattern synonyms.

(We are using `singletons` with `vinyl` to implement dynamic widgets, which are interactive GUI elements that have a list of properties that can be modified and processed; `singletons` is used to represent the ADT containing the fields we allow in the widgets and we pass things like `SClickHandler` or `SBackgroundColor` to a function called `setField` to modify a field of a widget. It will take another week or two of work but there should be a release soon – it's been an incredibly productive GSoC.)

**Comment by andrewthad** [comment]
If you're using this with vinyl (like I was), then you probably don't need anything near the full power of what `singletons` tries to accomplish. If you just want a more custom version of the TH function for creating the singleton types, you might be better off rolling/copying your own and not having a dependency on `singletons`. In [one of my earlier comments](https://github.com/goldfirere/singletons/issues/115#issuecomment-94296807), I think that I showed an example of something I had found that worked. (It used type synonyms rather than pattern synonyms though).

**Comment by gibiansky** [comment]
It looks like the `-XPatternSynonyms` approach works. Check out how [IHaskell does it](https://github.com/gibiansky/IHaskell/blob/master/ihaskell-display/ihaskell-widgets/src/IHaskell/Display/Widgets/Common.hs) if you are interested. The result is quite clean and avoids using the `S` prefix. (Downside, of course, is that it requires `PatternSynonyms`.)
