### ISSUE TITLE
Parallelize the testsuite

### ISSUE THREAD

**Issue by goldfirere** [goldfirere/singletons#123]
The `tasty` framework comes with a handy `-j` option that allows tests to be run in parallel. But this fails in `singletons` because some tests depend on others (like `Classes2` depends on `Classes`). It would be nice to fix this.

**Comment by RyanGlScott** [comment]
Do you remember why this was failing? I just tried running `cabal test --test-options=-j4` a couple of times, and everything appears to be working.

**Comment by goldfirere** [comment]
Some tests depend on others. For example `Singletons.PatternMatching` imports `Singletons.Nat`. So we need to make sure one is compiled before the other. Maybe the new setup is clever enough around all of this, but the old setup sure wasn't.

**Comment by RyanGlScott** [comment]
Sure. But keep in mind that we are literally just passing files to `ghc` here—`ghc` already knows how to deal with module dependencies during compilation! So perhaps I'm missing something obvious here, but it seems like this would work without any sort of fanciness (and my experimental results seem to confirm that hypothesis, at least).

**Comment by goldfirere** [comment]
Great -- then we can close the ticket.

**Comment by RyanGlScott** [comment]
Bah, I'm a darned fool. The reason I wasn't hitting this issue was because I wasn't linking with `threaded --with-rtsopts=N` on. When I do that, I can trigger the issues you were alluding to earlier, as demonstrated in [this Travis build](https://travis-ci.org/goldfirere/singletons/jobs/338628075#L1185).

I now realize that my statement in https://github.com/goldfirere/singletons/issues/123#issuecomment-363832244 failed to grasp the nuances of what was really going on. That comment was made assuming `ghc` was running in `--make` mode, but currently, we are passing `-c` instead! That means if we happen to get to a file with a dependency that hasn't been built yet, GHC will simply give up.

What's worse, we can't just swap out `-c` for `--make`, because then `-ddump-splices` would print out the dependencies in addition to the test case that uses them.

I briefly experimented with a setup where we'd run `ghc --make` (without `-ddump-splices`) beforehand immediately followed by `ghc -c -ddump-splices` to only dump the top-level test case, but I manage to hit a bizarre deadlock scenario on certain test cases, such as `T33`. I don't have the patience to figure out what's going on right now, so I'll re-open this ticket as a reminder.

**Comment by RyanGlScott** [comment]
https://github.com/feuerbach/tasty/issues/48 is relevant to this discussion.

**Comment by RyanGlScott** [comment]
Good news: `tasty` now has an experimental `dependencies` branch which implements an API for expressing test dependencies. I just pushed a proof-of-concept `parallel-tests` branch to `singletons` which modifies the test suite to use this API. On my machine (using four threads), this reduces the run time of the test suite from about 90 seconds to 30 seconds! Travis will only use two threads, which on my machine takes 50 seconds to run the tests—still an impressive time save!

Once a new version of `tasty` is released with this feature, I'll make a proper pull request from the `parallel-tests` branch.
