### ISSUE TITLE
Is it possible to promote higher-kinded type classes?

### ISSUE THREAD

**Issue by ocharles** [goldfirere/singletons#145]
The following

``` haskell
$(promote [d|
  class Col f where
    col :: f a -> a -> Bool
  |])
```

results in

```
       Cannot promote an applied type variable f_1627517956.
```

Is this going to be impossible to express with `singletons`?

**Comment by goldfirere** [comment]
Yes, this should be possible, but it's not right now -- this is an improvement that GHC 8 permits but `singletons` doesn't yet take advantage of.

To make this work, you'd need to remove `KProxy` in its entirety from `singletons`. This should be fine in GHC 8, because the poly-kinded `Proxy` can be promoted. Once everything is in terms of `Proxy` instead of `KProxy`, then you should be able to simply remove the check for promoting an applied type variable and it should work.

Happy to take a PR. :)

**Comment by ocharles** [comment]
Great! This sounds like a fun bit of work, I'll see what I can come up with.

**Comment by int-index** [comment]
With `TypeInType`, why use `Proxy` at all?

**Comment by goldfirere** [comment]
It's not `TypeInType` that obviates `Proxy`, it's `TypeApplications`. The problem is with eliminating `Proxy` is still twofold:
1. Template Haskell does not support visible type applications.
2. GHC still lacks support for visible type patterns, meaning that proxies are still sometimes necessary in data constructors. There's no theoretical challenge with visible type patterns, but the design isn't obvious; nor is the engineering. See [GHC#11350](https://ghc.haskell.org/trac/ghc/ticket/11350).

So, for now, we still need `Proxy`. But we shouldn't need `KProxy`!

**Comment by int-index** [comment]
`TypeApplications` eliminate a different use case for `Proxy`.

I meant that instead of replacing `SingKind (kproxy :: KProxy k)` with `SingKind (proxy :: Proxy k)` we can replace it with `SingKind k`, eliminating proxies altogether.
