### ISSUE TITLE
Nat Singletons in singletons prelude

### ISSUE THREAD

**Issue by meditans** [goldfirere/singletons#152]
I can write `0` to indicate the promoted type of kind `Nat`, in fact `:k 0` returns `0 :: Nat`. Now, I understand there should be the type `SNat 0` and the inhabitant of this type (something like `S0`) but I cannot understand how to write those. I'd like to use the definitions of the `singletons` library or the related ecosystem.

The analogue for `Bool` would be `Sing 'True` and `STrue`, which are indeed in the prelude. Could you point out what I'm missing, and how I should approach the problem instead?

EDIT:
To add a bit more context, in [this tutorial for an outdated version of singletons](https://www.schoolofhaskell.com/user/konn/prove-your-haskell-for-great-safety/dependent-types-in-haskell) there is this implementation of `replicate` for vectors:

    replicate :: SNat n -> a -> Vector a n
    replicate SZ     _ = Nil
    replicate (SS n) a = a :- replicate n a

but the author defines its own `data Nat = Z | S Nat`. I'd like instead to understand how all this is done with the singletons prelude.

**Comment by goldfirere** [comment]
You can import `Data.Singletons.TypeLits`, which gives you the singletons for the built-in `Nat` kind. Then you can say, for example, `sing :: Sing 0` to get what you've called `S0`. There is no way to write the singleton value directly -- you have to use `sing`. But these singletons are less useful than `data Nat = Z | S Nat` because you can't pattern-match on the built-in naturals, as they have no inductive structure.

I do hope this helps you along. If you have a concrete suggestion for where to put this documentation, I'll happily add it. Otherwise, if you're satisfied, please close the ticket. Thanks!

**Comment by goldfirere** [comment]
Closing with lack of response. Do reopen if you feel it helpful.
