### ISSUE TITLE
"Cannot find" errors when deriving due to a lack of imports

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#190]
There's a bit of discrepancy among the derivable type classes when it comes to what you need to import to actually make them work. To explain what I mean, consider this example:

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Singletons.TH

$(singletons [d| data T = T deriving Eq |])
```

This compiles, needing only an import of `Data.Singletons.TH`. If you try `Enum` instead, however:

```haskell
$(singletons [d| data T = T deriving Enum |])
```

You're greeted with this rather confusing error message:

```
Bug.hs:12:3: error:
    Cannot find class declaration annotation for Data.Singletons.Prelude.Enum.Enum
   |
12 | $(singletons [d| data T = T deriving Enum |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Bug.hs:12:3: error: Q monad failure
   |
12 | $(singletons [d| data T = T deriving Enum |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Similarly with `Bounded`:

```haskell
$(singletons [d| data T = T deriving Bounded |])
```
```
Bug.hs:12:3: error: Cannot find type annotation for MinBound
   |
12 | $(singletons [d| data T = T deriving Bounded |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Bug.hs:12:3: error: Q monad failure
   |
12 | $(singletons [d| data T = T deriving Bounded |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

`Ord` also gives an error (although not quite as confusing):

```haskell
$(singletons [d| data T = T deriving (Eq, Ord) |])
```
```
Bug.hs:12:3: error:
    • Data constructor not in scope: SEQ :: Sing 'EQ
    • Perhaps you meant ‘EQ’ (imported from Prelude)
   |
12 | $(singletons [d| data T = T deriving (Eq, Ord) |])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The solution to the previous three errors is to import `Data.Singletons.Prelude`. But it feels like this shouldn't be necessary, since:

1. `Eq` doesn't require it.
2. Surely `singletons` can manage the import voodoo behind the scenes for you?

**Comment by goldfirere** [comment]
`singletons` can manage import voodoo only for modules that are transitively available. It seems that the symbols in question are not available, even transitively.

I say the solution is to add more import statements to `Data.Singletons.TH` to make the problems go away.

**Comment by goldfirere** [comment]
`singletons`-generated code can have several different sorts of names. Some names are declared in `Data.Singletons.Names` and are available whether or not the names are in scope. (This is what I alluded to previously when thinking about transitive imports.) Other names are generated by mangling existing names (that is, prepending `S` and such). This second category requires that the new names are really in scope. Because derived instances are built by generating the original, non-singleton instances and then promoting/singling, the names used there are of the mangled variety.

I thus propose that `TH` export the necessary symbols. My previous comment was just wrong.
