### ISSUE TITLE
Promote IsString

### ISSUE THREAD

**Issue by SamuraiJack** [goldfirere/singletons#247]
Hello,

I'm trying to singletonize the data structure with String/Text, using singletons 2.2. I'm planning to re-use this structure (along with associated methods) on both term and type level.

This fails with: `Could not deduce: DemoteRep Text ~ Text`
```haskell
$(singletons [d|
    data Some = Some {
        someName       :: Text
    } 
    |])
```

I've tried a workaround from #76. It does not compile with singletons 2.2 already, so I changed it a bit (replaced proxies)

This still fails however, with `Could not deduce: DemoteRep FooTerm ~ FooTerm`

```haskell
data Foo = Bar Symbol
data FooTerm = BarTerm Text   -- Integer is the closest term-level equiv.

data instance Sing (x :: Foo) where
  SBar :: Sing n -> Sing (Bar n)

instance SingKind Foo where
  type DemoteRep Foo = FooTerm
  fromSing (SBar n) = BarTerm $ pack (fromSing n)
  toSing (BarTerm n) = case toSing (unpack n) of
               SomeSing n' -> SomeSing (SBar n')

$(singletons [d|

    data Some = Some {
        someName       :: FooTerm
    } 
    |])
```

My idea is to define a custom singleton for "FooTerm" and then re-use it in the code being promoted (as I'm planning to add functions, working with "Some" and "FooTerm"). I'll only need the string equality comparison from the operations over the FooTerm.

Any advise?

**Comment by mstksg** [comment]
The typical way to do this is

```haskell
$(singletons [d|
  data Some sym = Some {
      someName :: sym
  }
  |])
```

For the promoted `Some` kind, you'd use `Some Symbol`, and for the unpromoted type, you'd use `Some Text`.

**Comment by SamuraiJack** [comment]
Thanks, this seems to work a bit better. However, is it possible to singletonize values in this setup? It seems it will be needed 2 different declarations for the same data:

```
$(singletons [d|

    data Some sym = Some {
        someName       :: sym
    } deriving Show

    |])

-- term data   
someValue :: Some String

someValue = Some {
    someName = "s"
}

-- type level data
$(promoteOnly [d|
    someValue :: Some Symbol

    someValue = Some {
        someName = "s"
    }
    |])
```

**Comment by mstksg** [comment]
(by the way, note that the demotion of `Symbol` is `Text`, not `String`.  This is because `String` is just `[Char]`, so is naturally promoting/demoting with a list).

The only way to singletonize functions or values is to write them in a way that is polymorphic on the type parameter, using appropriate constraints as you need them (like `Eq` or `Ord`).  This works better with functions, but for values like you gave, it is a little tricker because you want an actual Text/Symbol there.

I'm not sure exactly what the best way is, but you could treat both of them polymorphic on the type variable by using `fromString s` and `IsString` instead of the literals and specific type variables:

```haskell
$(singletons [d|
  someValue :: IsString s => Some s
  someValue = Some { someName = fromString "s" }
  |])
```

This should work, but we do need to promote the `IsString` typeclass:

```haskell
$(singletonsOnly [d|
    class IsString a where
        fromString :: Symbol -> a
  |])

instance PIsString Symbol where
    type FromString s = s

instance SIsString Symbol where
    sFromString = id
```

And so:

```haskell
:kind! (SomeValue :: Some Symbol)
  = 'Some "s"
```

Not sure if this is the best way, but if it is, maybe `IsString` is worth promoting, @goldfirere ?

**Comment by goldfirere** [comment]
@mstksg's suggestions are good. In the end, I think you want #82, which we don't have yet.

**Comment by goldfirere** [comment]
And, yes, promoting `IsString` sounds very reasonable, as would be general support for promoted overloaded strings.

**Comment by SamuraiJack** [comment]
@mstksg Thanks for the help, it works! Almost :)

It works when declaration of Some and definition of data are in the same module. However it fails, if in one module I only declare the Some:

```
module Definitions(
    Some(..), SomeSym0(..), SSome(..), PIsString, SIsString, FromStringSym0, sFromString, FromString
) where

import GHC.TypeLits

import Data.Proxy
import Data.Kind
import Data.Text
import Data.String

import Data.Singletons.TH
import Data.Singletons.TypeLits
import Data.Singletons.Prelude.List

$(singletonsOnly [d|
    class IsString a where
        fromString :: Symbol -> a
        
    |])

instance PIsString Symbol where
    type FromString s = s

instance SIsString Symbol where
    sFromString = id


$(singletons [d|

    data Some sym = Some {
        someName       :: sym
    } deriving Show

    |])

```

And trying to define the data in another module:

```
module Information(
) where

import GHC.TypeLits

import Data.Proxy
import Data.Kind
import Data.Text
import Data.String

import Data.Singletons.TH
import Data.Singletons.Prelude.List
    
import Definitions

$(singletons [d|
    someValue :: IsString s => Some s
    someValue = Some { someName = fromString "s" }

    |])
```

The error is:
```
    • Data constructor not in scope: SSome :: Sing t -> Sing ('Some t)
    • Perhaps you meant ‘Some’ (imported from Horn.Schema.Definitions)
```
which is weird, since SSome is definitely exported from "Definitions"..
It works if I export everything, but I'd prefer to be explicit..

**Comment by mstksg** [comment]
Ah, this is actually a very basic Haskell thing that trips a lot of Haskell beginners up when they are learning the language.  And occasionally, experienced Haskellers run into it too because they stopped looking for it.

Your issue is that you gave the data constructor the same name as your type constructor, and you exported one (the type constructor) and not the other (the data constructor).  It happens a lot in basic Haskell, but I can sympathize with the surprise if you aren't watching out for it when incorporating other more advanced Haskell, too.

In the context of singletons, The (asking-for-errors) declaration:

```haskell
data Some s = Some s
```

Actually creates *two* things `SSome`:

1. the **data family instance constructor**,

    ```haskell
    data instance Sing where
        SSome :: s -> Sing (Some s)
    ```

    (So, `SSome` is a *data constructor* for the type `Sing`, just like `Just` is a data constructor for the type `Maybe`)

2. the **type synonym**:

    ```haskell
    type SSome = Sing :: Some s -> Type
    ```

And, also, when you define an export list, **you don't export data constructors**.  It's even not possible in Haskell (see https://www.haskell.org/onlinereport/haskell2010/haskellch5.html).  I suspect that you already knew this, if you have been using Haskell for a while.

So, when you `module Definitions where (SSome(..))`, you're actually exporting **the type synonym**, and *not* the data constructor.  Because remember, you can't export data constructors in Haskell...that's just not a thing.  So you aren't exporting the `SSome` data constructor at all, here, but the type synonym.

If you compile with `-Wall`, this should actually give you a warning, so you know that something fishy is happening.  I do recommend compiling with `-Wall` when developing Haskell, as it helps catch a lot of things like this :)

But probably what could have fixed this from the beginning is just not using the same identifier for the type constructor (Some) as the data constructor (Some).  This is already a confusing thing to do in regular Haskell, and is made even more confusing from the fact that we're now promoting a data constructor `Some` to a type constructor `'Some`, where there is already a type constructor `Some` defined, heh.  This makes it even a bigger headache than usual.  But, yeah, if you had named your data constructors differently from your type constructors, this wouldn't have ended up being an issue.  You might have had

```haskell
data Some s = MkSome s
```

Then the error would have been that you didn't export `SMkSome`, and then you would have looked at your export list to see that you indeed did not export any `SMkSome`.

Then you can add `SMkSome`, the *data constructor*, to your export list, like you would any other data constructor -- in parentheses after the type name.

```haskell
module Definitions where (Sing(SMkSome), ...)
```

(because `SMkSome` is a data constructor for the type (data family) `Sing`)

**Comment by SamuraiJack** [comment]
Oh, I see, thanks for the explanations. I'm jumping straight to [the deep waters](https://medium.com/@nickolay8/switching-to-haskell-3164f089c8b) so am not quite aware about all such small tricks.

Should I close this ticket or keep it opened for the built-in promotion of "IsString" (or another way to deal with promoting overloaded strings)?

**Comment by RyanGlScott** [comment]
I think `IsString` would be a natural fit for `singletons`. After all, several people (ab)use the promoted `FromInteger` type in `PNum` to write code that works over both numeric types and type-level `Nat`s, so a `FromString` type in `PIsString` seems like a natural analog for `Symbol`s.

It would also be quite natural to desugar `Symbol` literals down to calls to `FromString ...` when `OverloadedStrings` is enabled. (The [`qIsExtEnabled`](https://www.stackage.org/haddock/lts-9.3/template-haskell-2.11.1.0/Language-Haskell-TH-Syntax.html#v:qIsExtEnabled) function from `template-haskell` provides a convenient way to check for this.)

To answer your question, @SamuraiJack:

> Should I close this ticket or keep it opened for the built-in promotion of "IsString" (or another way to deal with promoting overloaded strings)?

I would be fine with either:

1. Closing this ticket in favor of a new one
2. Keeping this ticket, but changing the title to reflect its new purpose

**Comment by SamuraiJack** [comment]
Ok, renamed to "Promote IsString", please correct if needed.
