### ISSUE TITLE
Errors in promoted functions

### ISSUE THREAD

**Issue by SamuraiJack** [goldfirere/singletons#248]
If I'm correct "singletons" uses its own "Error" type for reporting error, which does not result in type error during compilation, but just silently wraps the type into the "Error".

```haskell
$(singletons [d|
    a :: Bool

    a = head []

    |])

data Some s = Some

b :: Some A

b = Some
```
compiles fine, its just the type is weird:
```haskell
> :t b
b :: Some (Error "Data.Singletons.List.head: empty list")
```
Should the `TypeError` facility from https://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-TypeLits.html be used instead? It results in actual compilation error, with user message. Or am I missing something?

**Comment by goldfirere** [comment]
Sounds good to me. @RyanGlScott ?

**Comment by RyanGlScott** [comment]
This ticket largely overlaps with #160. To summarize that issue:

1. There's a design choice to be had here. Picking `Error` gives you a type family that doesn't reduce, whereas `TypeError` produces a compile-time exception. There are situations where you might want one or the other, so I'm hesitant to make all uses of `error` promote to `TypeError` unilaterally.
2. Given that, a natural inclination would be to create a term-level function `typeError :: ErrorMessage -> a` which promotes to the `TypeError` type family. This _almost_ works in today's `singletons`, but there's a really annoying obstacle in the form of the [`Text` constructor for `ErrorMessage`](https://www.stackage.org/haddock/lts-9.3/base-4.9.1.0/GHC-TypeLits.html#t:ErrorMessage):

   ```haskell
     | Text Symbol
   ```

   As chronicled in #82 (and #247, more recently), we can't use the `Text` symbol at the value level, only the type level. We could introduce a separate `ErrorMessageTerm` data type with a constructor `TextTerm :: Text -> ErrorMessageTerm`, but even if we did this, we still wouldn't be able to write the same code at the value and type level, which stinks.

   If we could redesign `TypeError` from scratch, we could make `Text` parameterized over a symbol type, as is done in https://github.com/goldfirere/singletons/issues/247#issuecomment-326762302. But I doubt we'd get away with that today.

**Comment by goldfirere** [comment]
I had a niggling feeling things were more complicated than I thought -- which is why I wanted your opinion. Thanks for the explanation.

**Comment by SamuraiJack** [comment]
"typeError" sounds good for me, with some form of workaround for a `Text/Symbol` issue..

**Comment by SamuraiJack** [comment]
Is it possible to express the promotion of "typeError" to "TypeError" inside the "singleton" blocks in the user code?

```haskell

typeError = sSomeMagic

$(singletons [d|
    a = if (b) typeError $ fromString "whatever" else c
    |])

**Comment by RyanGlScott** [comment]
Indeed, what `sSomeMagic` should be is precisely the question that I can't figure out an answer to. The question we must ask ourselves is: what should `typeError` do as a value-level function? Presumably, it should throw a runtime exception, so the question becomes how we take one of [these](https://www.stackage.org/haddock/lts-9.3/base-4.9.1.0/src/GHC-TypeLits.html#ErrorMessage):

```haskell
data ErrorMessage = Text Symbol
                  | forall t. ShowType t
                  | ErrorMessage :<>: ErrorMessage
                  | ErrorMessage :$$: ErrorMessage
```

and turn it into a human-readable exception. Unfortunately, `ErrorMessage` doesn't give us much to work with. `ShowType` is completely useless, since we can't know anything about the type of its field. `Text` is also useless, since we can't turn a `String`/`Text` value into a `Symbol` value (or vice versa). And the `(:<>:)`/`(:$$:)` constructors are just for formatting. So we're not left with any options.

**Comment by RyanGlScott** [comment]
One "solution" would be to make `typeError = const (error "TypeError")`. But this isn't a very satisfying solution, since now every use of `TypeError` would give the same error message, and that would arguably be a regression in error message quality.

**Comment by SamuraiJack** [comment]
`typeError = const (error "TypeError")` this will work for now in my case. I just need to have a compile-time exception. How such promotion can be expressed, so that later it can be "picked up" by the `$(singletons`?

**Comment by RyanGlScott** [comment]
This _almost_ works:

```haskell
{-# LANGUAGE GADTs #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Promotion.TH
import Data.Singletons
import GHC.TypeLits

typeError :: ErrorMessage -> a
typeError = const (error "TypeError ...")

$(genDefunSymbols [''ErrorMessage])

-- Due to GHC #12048, we can't just use $(genDefunSymbols [''TypeError]).
-- As a workaround, we write the defunctionalization symbols for TypeError by hand.
data TypeErrorSym0 :: ErrorMessage ~> b
type instance Apply TypeErrorSym0 x = TypeErrorSym1 x

type family TypeErrorSym1 (a :: ErrorMessage) :: b where
  TypeErrorSym1 x = TypeError x

$(promote [d| myHead :: [a] -> a
              myHead (x:_) = x
              myHead []    = typeError (Text "myHead: empty list")
            |])

f :: MyHead '[Int]
f = 42

g :: MyHead '[]
g = error "boom"
```

But there's one remaining hiccup—compiling this gives:

```
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:27:3: error:
    • Couldn't match expected type ‘Symbol’ with actual type ‘[Char]’
    • In the first argument of ‘Text’, namely ‘"myHead: empty list"’
      In the first argument of ‘typeError’, namely
        ‘(Text "myHead: empty list")’
      In the expression: typeError (Text "myHead: empty list")
   |
27 | $(promote [d| myHead :: [a] -> a
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

Probably the simplest solution would be to add an `IsString Symbol` instance in `Data.Singletons.TypeLits` (see [here](https://github.com/goldfirere/singletons/blob/fe370c4a26088cac370a14dc6be342194103f131/src/Data/Singletons/TypeLits.hs#L60) for examples of how this is done). Then you'd just need to enable `OverloadedStrings` and everything would Just Work™... I think :)

Would you like to add this `IsString Symbol` instance, @SamuraiJack? It might also tie into #247 quite nicely (although #247 isn't required to fix this particular issue).

**Comment by SamuraiJack** [comment]
This looks very promising, thanks! I'll give it try later today.

If you are about a PR - yes, I'm willing to do it.

**Comment by SamuraiJack** [comment]
Hm.. Something I'm missing:

My module now looks like this:

```haskell
module Horn.Schema.Definitions(
) where

import GHC.TypeLits

import Data.Proxy
import Data.Kind
import Data.String

import Data.Singletons.TH
import Data.Singletons.TypeLits
import Data.Singletons.Prelude
import Data.Singletons.Prelude.Maybe
import Data.Singletons.Prelude.List

no_term_level_syms :: a
no_term_level_syms = error "The kind `Symbol` may not be used at the term level."

typeError :: ErrorMessage -> a
typeError = const (error "TypeError ...")

$(genDefunSymbols [''ErrorMessage])

-- Due to GHC #12048, we can't just use $(genDefunSymbols [''TypeError]).
-- As a workaround, we write the defunctionalization symbols for TypeError by hand.
data TypeErrorSym0 :: ErrorMessage ~> b
type instance Apply TypeErrorSym0 x = TypeErrorSym1 x

type family TypeErrorSym1 (a :: ErrorMessage) :: b where
    TypeErrorSym1 x = TypeError x

instance IsString Symbol where
    fromString  = no_term_level_syms

$(promote [d| 

    myHead :: [a] -> a

    myHead (x:_) = x
    myHead []    = typeError (Text "myHead: empty list")

    |])

f :: MyHead '[Int]
f = 42

g :: MyHead '[]
g = error "boom"
```

And it compiles fine, w/o compilation error. In fact, in ghci I see the type of `g` as:
```
*Horn.Schema.Definitions> :t g
g :: (TypeError ...)
```

**Comment by RyanGlScott** [comment]
@SamuraiJack, that's what I would have expected. My suggestion was to maks a PR which adds this `IsString Symbol` instance to `Data.Singletons.TypeLits` so that you won't have to define it locally (it is an orphan instance after all, so it'd be nice to have a canonical home for it).

I'm less enthusiastic about enshrining that particular version of `typeError` in `singletons`, since it doesn't do the same things at the value and type levels. But I suppose I could be convinced to add it if enough people find it useful.

**Comment by SamuraiJack** [comment]
Right, I'm trying to make it work locally before submitting a PR.

Isn't compile-time exception a good thing? To break early on various errors. It even exists in core GHC already.

I wonder how the `g` has a type of `TypeError` and there were no compilation error. Also curious what is a triple dot in the type for `g`... Is it some different `TypeError` and not the one from `GHC.TypeLits`?

**Comment by RyanGlScott** [comment]
> I wonder how the `g` has a type of `TypeError` and there were no compilation error. 

If I understand your comment, you're confused that a function like this:

```haskell
g :: MyHead '[]
g = error "boom"
```

Compiles at all? That's understandable—it's a known quirk. [Trac #13775](https://ghc.haskell.org/trac/ghc/ticket/13775) explains in greater detail why this happens, but the gist of it is that custom type erros are thrown only when there's an unsolved constraint that involves `TypeError`. That is, this compiles:

```haskell
g :: MyHead '[]
g = error "boom"
```

Because the type of `error "boom"` is `forall a. a`, and GHC readily unifies `a` with `MyHead '[]`, so there's no unsolved constraints. On the other hand, this would give a custom type error:

```haskell
g' :: MyHead '[]
g' = ()
```

Because we would have an unsolved constraint of the form `() ~ MyHead '[]`, and here `MyHead '[]` reduces down to something which mentions `TypeError`. It's all a bit unsettling, but at least you can be assured that GHC will _eventually_ catch you if you try to use `g` in any substantive way.

> Also curious what is a triple dot in the type for `g`... Is it some different `TypeError` and not the one from `GHC.TypeLits`?

No, that's `GHC.TypeLits.TypeError` alright. It's displaying that like because by default, [`TypeError` types are pretty-printed as `TypeError ...`](http://git.haskell.org/ghc.git/blob/464396d00450efb58330987ebac4735902ba0f01:/compiler/iface/IfaceType.hs#l899) to avoid cluttering the screen when pretty-printing, as these custom type errors can be quite long. To display the full shebang, you have to enable the `-dppr-debug` flag.

**Comment by SamuraiJack** [comment]
Ah, I see now, thanks for the explanations!

**Comment by RyanGlScott** [comment]
The `IsString Symbol` orphan instance will be added in #268.

Also, I came up with a much more promising way to support custom `TypeError`s in `singletons`. See https://github.com/goldfirere/singletons/issues/160#issuecomment-338246486 for the juicy details.

**Comment by RyanGlScott** [comment]
#268 has been merged.

The remaining issue here is about how to handle `TypeError`, but I'll close this in favor of the discussion in #160.
