### ISSUE TITLE
Sigma types

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/singletons#256]
Being a dependently typed* programming language, one thing I often desire in `singletons`-flavored Haskell is a proper dependent pair:

```haskell
{-# LANGUAGE AllowAmbiguousTypes #-}
{-# LANGUAGE GADTs #-}
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeInType #-}
module Sigma where

import Data.Kind
import Data.Proxy
import Data.Singletons

data Sigma (s :: Type) :: (s ~> Type) -> Type where
  (:&:) :: Sing (fst :: s) -> t @@ fst -> Sigma s t
infixr 4 :&:
type Σ (s :: Type) (t :: s ~> Type) = Sigma s t -- Because I can

proj1 :: SingKind s => Sigma s t -> Demote s
proj1 (a :&: _) = fromSing a

proj2 :: Sigma s t -> (forall (fst :: s). t @@ fst -> r) -> r
proj2 ((_ :: Sing (fst :: s)) :&: b) f = f @fst b
```

Would you be OK with adding something like this to `singletons`?

**Comment by mstksg** [comment]
I do use a very similar type from other libraries when working with singletons.  I have to import it externally every time, if I want to be more generic (with `~>` and `@@`) then I usually do make my own.

I would personally advise against using `:&:` because it's already the name of a popular type used by many libraries and also a part of base:

```haskell
    data (f :&: g) a = InL (f a) | InR (g a)
```

as a functor sum, and is a central type to the "data types a la carte" style of programming.  Just my suggestion :)

**Comment by mstksg** [comment]
Actually, just realized now that `:&:` is used as the type constructor and not the data constructor, so there might not be any immediate issue with collisions.

**Comment by goldfirere** [comment]
No objection from me...

**Comment by RyanGlScott** [comment]
I'm not sure what `(:&:)` type from `base` you're referring to. Might you be thinking of [`(:+:)`](http://hackage.haskell.org/package/base-4.10.0.0/docs/GHC-Generics.html#t::-43-:) from `GHC.Generics`?

That being said, I don't have a strong opinion on whether this constructor is called `(:&:)`, `(:=>)`, `MkSigma`, or something else.

**Comment by mstksg** [comment]
@RyanGlScott ah, so sorry, you're right!  `:&:` is probably great in that case.
