### ISSUE TITLE
Promote function that constructs functions

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#257]
I want to express some kind of "map" (each element has it's own function) of an heterogenous List and I don't know how I can express the relevant type-level function:

```haskell
$(promoteOnly [d|
    toArrow :: [Type] -> [Type] -> [Type -> Type]
    toArrow inputs outpus = zipWith (->) inputs outpus
  ])
```

I hope my question is sensible and I didn't mix up the terms!

**Comment by RyanGlScott** [comment]
Before I dive too much into specifics, I want to make sure I understand what you're trying to accomplish here. Would this be the output you'd expect from this `ToArrow` type family?

```haskell
ToArrow '[Int, Char] '[Bool, Double] = '[Int -> Bool, Char -> Double]
```

The reason I ask is because your `[Type -> Type]` return kind is throwing me off. `'[Int -> Bool, Char -> Double] :: [Type]`, not `[Type -> Type]`.

**Comment by LeanderK** [comment]
yeah, `[Type -> Type]` is wrong but i am not sure what the right type is. Looking at it again it's probably also Type.

**Comment by RyanGlScott** [comment]
OK. I suggest not trying to use `promote` to write this, since it doesn't make sense to write the `(->)` type constructor in a term definition like what you're proposing. Instead, I recommend just writing the type family directly.

The most straightforward way to write this would be like so:

```haskell
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Foo where

import Data.Kind

type family ZipWith (f :: a -> b -> c) (x :: [a]) (y :: [b]) :: [c] where
  ZipWith _ '[]    _      = '[]
  ZipWith _ _      '[]    = '[]
  ZipWith f (x:xs) (y:ys) = f x y : ZipWith f xs ys

type family ToArrow (i :: [Type]) (o :: [Type]) :: [Type] where
  ToArrow inputs outputs = ZipWith (->) inputs outputs
```

That does accomplish what you seek.

-----

Now, you might be wondering "why can't I just use the promoted `ZipWith` type family from `singletons`"? Well you can, but it's slightly more involved, since the kind of `ZipWith` from `singletons` is not `(a -> b -> c) -> [a] -> [b] -> [c]`, but rather:

```haskell
ZipWith :: (a ~> b ~> c) -> [a] -> [b] -> [c]
```

Notice the use of the squiggly function arrow `(~>)` in `(a ~> b ~> c)`. This is a trick that `singletons` uses to allow partial application of type families (something which is normally impossible in GHC). For instance, note that you can't say `ZipWith Div a b`, but instead you must use `ZipWith DivSym0 a b`, where `DivSym0` is a _defunctionalization symbol_ for `Div` that expects 0 arguments. That is, while `Div` is of kind `Nat -> Nat -> Nat`, `DivSym0` is of kind `Nat ~> Nat ~> Nat`.

So if you want `ZipWith '[Int] '[Bool]` to produce `Int ~> Bool` instead of `Int -> Bool`, you can do this (I'm assuming `singletons-2.3.1` in the example below, as the version of `singletons` in HEAD has different syntax for infix defunctionalization symbols):

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE TypeInType #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import Data.Kind
import Data.Singletons.Prelude
import Data.Singletons.TH

$(genDefunSymbols [''(~>)])

type family ToArrow (i :: [Type]) (o :: [Type]) :: [Type] where
  ToArrow inputs outputs = ZipWith (:~>$) inputs outputs
```

Here, `(:~>$) :: Type ~> Type ~> Type` is a defunctionalization symbol for `(~>)`. Normally, `singletons` provides defunctionalization symbols for everything it exports, but for some reason we don't do this for `(~>)` (I should fix that...), so I had to manually defunctionalize it with that `$(genDefunSymbols [''(~>)])` bit of Template Haskell.

-----

Does this help?

**Comment by LeanderK** [comment]
yes, this helps and I think I also understood the problem. Thank you!

**Comment by RyanGlScott** [comment]
Awesome! Do keep this ticket open, since I want to use it as a reminder to fix that `(~>)` defun symbol issue I mentioned in https://github.com/goldfirere/singletons/issues/257#issuecomment-335919128.
