### ISSUE TITLE
Partial Partial Application possible?

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#262]
Correct me if I am wrong, there is not too much information out there.
`(~>)` makes partial application possible with singletons, but is it possible to only replace some arrows?
Lets say I have a type: `Replicate :: Nat -> Type -> Type`, is it possible to generate `ReplicateP :: Nat ~> Type -> Type`, which I could partially apply to optain `ReplicateP2 :: Type -> Type`? As I understood it genDefunSymbols only transforms all the arrows into partially applied arrows.

**Comment by RyanGlScott** [comment]
`genDefunSymbols` produces defunctionalization symbols for all possible partial applications of a type function. For example, if you had `Replicate :: Nat -> Type -> Type`, then `$(genDefunSymbols [''Replicate])` would produce:

* `ReplicateSym0 :: Nat ~> Type ~> Type` (can partially apply with no arguments)
* `ReplicateSym1 :: Nat -> Type ~> Type` (can partially apply, provided one argument of kind `Nat` is given)
* `ReplicateSym2 :: Nat -> Type -> Type` (this is just a synonym for `Replicate`)

**Comment by LeanderK** [comment]
I am a bit confused by the order of `(~>)`. Does `ReplicateSym1` mean I can obtain `Type ~> Type` or `Type -> Type`? (And does this matter?)

**Comment by RyanGlScott** [comment]
> Does `ReplicateSym1` mean I can obtain `Type ~> Type` or `Type -> Type`?

No. You can go from `a -> b` to `a ~> b` (through [`TyCon1`](https://github.com/goldfirere/singletons/blob/429e2859c8871a1880b40dfad4c08432c8dd4176/src/Data/Singletons/Internal.hs#L137)), but not the opposite direction.

If it helps, think of a kind before a `~>` arrow as partially appliable, but a kind before `->` one that must be provided to apply the function. Then the order of `ReplicateSym0` through `ReplicateSym2` will make more sense, since each one gradually requires more arguments to be provided.

**Comment by LeanderK** [comment]
ok, so just to be sure `Nat ~> (Type -> Type)` this is not possible.

**Comment by RyanGlScott** [comment]
It's not accurate to say that it's impossible, since you could have a `type family F (a :: Nat) :: Type -> Type`. Then defunctionalizing `F` would give you `FSym0 :: Nat ~> (Type -> Type)`. But of course, giving `F` this return kind limits you in the way you can define `F`, since this would be legal:

```haskell
type family F (a :: Nat) :: Type -> Type where
  F a = Maybe
```

But not this:

```haskell
type family F (a :: Nat) :: Type -> Type where
  F a b = b
```

**Comment by LeanderK** [comment]
okay, interesting. Thank you.
