### ISSUE TITLE
Relationship between type-indexed TypeRep and Sing (for non-Type-kinds)

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/singletons#280]
This isn't an issue, rather something that has been on my mind lately.

----

`TypeRep (a::Type)` can be used to represent singletons of types (`Sing (a::Type)`): This is discussed in Richard's thesis

> However, passing types at runtime is sometimes necessary, and using the type **Type** to do so is a natural extension of what is done today. Indeed, today’s `TypeRep` .. is essentially a singleton for **Type**. As Dependent Haskell removes other singletons, so too will it remove `TypeRep` in favor of dependent pattern matching on **Type**. 

And several other places.. the documentation talks about `Sing (a :: Type) where STypeRep :: Typeable a => Sing a`.. Richard defines [`type instance Sing = (TypeRep :: Type -> Type)`](https://gist.github.com/goldfirere/846c3faf7640e27025f0#file-basics-hs-L130) + appears in Trac comments.

But these only consider it as a singleton for **Type**, but that's selling `TypeRep` short! It seems we can define singletons for other types like naturals `N` with + singleton constructors `SO :: SN 'O` and `SS :: SN (n::N) -> SN ('S n::N)` as pattern synonyms (with our handy `TypeRep` pattern from #273)

```haskell
-- pattern TypeRep :: () => Typeable a => TypeRep a

type SN = (TypeRep::N -> Type)

pattern SO :: () => O~o => SN o
pattern SO <- (eqTypeRep (TypeRep @O) -> Just HRefl)
  where SO  = TypeRep @O

-- There is some subtlety in getting the right constraints
pattern IsS :: () => S~~s => TypeRep s
pattern IsS <- (eqTypeRep (TypeRep @S) -> Just HRefl)
  where IsS  = TypeRep @S

pattern SS :: () => forall (nn::N). S nn~sn => SN nn -> SN (sn::N)
pattern SS sn      <- App IsS sn
  where SS TypeRep  = TypeRep @(S _)
```

which lets us define the usual `replicate` function:

```haskell
replicate :: SN n -> a -> Vec a n
replicate SO      _ = VNil
replicate (SS sn) a = VCons a (replicate sn a)
```

So what exactly is the relationship between type-indexed `TyRep` and `Sing`? I feel like I'm missing something, is one more powerful, dependent pattern matching may subsumes both but does one subsume the other.. Feel free to close or ignore

**Comment by goldfirere** [comment]
You're right of course. Stephanie and I ruminated a year ago that the new `TypeRep` is really one singleton to rule them all. I believe you could get all the behavior that we want from singletons (the datatype definitions only, not the other magic that `singletons` provides) just from `TypeRep`. I briefly considered re-engineering `singletons` to do exactly that, but I wasn't sure the concrete benefit, and there are downsides, because working with `TypeRep` seems much less perspicuous that working with bespoke singletons.

In more direct answer to your question: I believe that `TypeRep` is strictly more powerful than singletons, because `TypeRep` handles types of kind `Type` (and, more generally, `... -> Type`) and singletons don't. However, if we restrict ourselves to algebraic datatypes, I believe that `TypeRep` and singletons are exactly equal in power.

**Comment by RyanGlScott** [comment]
I believe that this question (this reads more like a question report than a bug report) has been answered quite thoroughly, so I'll opt to close this. Do re-open if there is something more to this!

**Comment by Icelandjack** [comment]
Yeah it's just a question, closing it is fine Ryan.

Perfect, thanks. I will continue to think about this. (one benefit of `Typeable` / `TypeRep` being compiler generated is that two modules can define separate `SFalse` pattern synonyms that are compatible because they use the same underlying `TypeRep (False::Bool)` without conflict / orphans)

Q: `Constraint` singleton?

```haskell
data instance Sing (c::Constraint) where
  Dict :: c => Sing c

instance c => SingI (c::Constraint) where
  sing :: Sing c
  sing = Dict
```

Q: How about detypeclassized symbols like `EqSym0`? `SLambda` matches `Sing (a::Type ~> Constraint)` but this requires us to construct a function `forall xx. Sing xx -> Sing (Eq xx)`

```haskell
data EqSym0 :: Type ~> Constraint

type instance EqSym0 `Apply` a = Eq a

instance SingI EqSym0 where
  sing :: Sing EqSym0
  sing = SLambda lam where

    lam :: forall xx. Sing xx -> Sing (Eq xx)
    lam = ...
```

**Comment by Icelandjack** [comment]
Having discussed with @RyanGlScott: I mistakenly thought `Dict` was a singleton, and mirroring [`Data.Singletons.TypeRepStar`](https://hackage.haskell.org/package/singletons-2.3.1/docs/Data-Singletons-TypeRepStar.html)

```haskell
newtype instance Sing (z :: Constraint) where
 SConstraintRep :: forall (c :: Constraint). TypeRep c -> Sing c
```

and then we can define [`SingI` instances for the defunctionalization symbols](https://github.com/goldfirere/singletons/issues/252)

```haskell
instance SingI (TyCon1 Eq) where
  sing :: Sing (TyCon1 Eq) 
  sing = SLambda $ \(STypeRep b) -> 
    withTypeable b 
      (SConstraintRep typeRep)
```

**Comment by goldfirere** [comment]
GHC really shouldn't accept both `newtype instance Sing (z :: Type)` and `newtype instance Sing (z :: Constraint)`. That's just plain wrong. See [here](https://github.com/ghc-proposals/ghc-proposals/pull/32). Let's not tickle this hole in the type system intentionally, especially because I think we'll close it, preventing both of these instances from existing.
