### ISSUE TITLE
Lazy Bool operations

### ISSUE THREAD

**Issue by odr** [goldfirere/singletons#299]
Singletons.TH generate lazy `if` statement but strict boolean operations (`&&`, `||`). E.g.
```Haskell
singletons [d|
  testIf :: Nat -> Bool
  testIf n = if n <= 0 then False else if n > 0 then False else testIf (n-1)
  testAnd :: Nat -> Bool
  testAnd n = if n <= 0 then False else (n<=0 && testAnd (n-1))
  |]
```
Now
ghci> :kind! (TestIf 1000) 
is fast
ghci> :kind! (TestAnd 1000)
is slow

Similar problem with
ghci> sTestAnd (sing::Sing 1000)
return "reduction stack overflow"

I suppose that boolean operations must be also lazy.

-- singletons-2.3.1

**Comment by RyanGlScott** [comment]
It depend on what you mean by "lazy". At runtime, `sIf` is as lazy at it can be:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeApplications #-}

import Data.Singletons.Prelude
import Data.Singletons.TypeLits

main :: IO ()
main = do
  print $ fromSing $ sIf STrue  STuple0 err
  print $ fromSing $ sIf SFalse err     STuple0
  where
    err = sError $ SSym @"Too strict"
```

This prints out:

```haskell
()
()
```

Like you'd expect. The real problem lies with the `If` type family. Its [definition](https://hackage.haskell.org/package/base-4.10.1.0/docs/src/Data.Type.Bool.html#If) is correct:

```haskell
type family If cond tru fls where
  If 'True  tru  fls = tru
  If 'False tru  fls = fls
```

The problem is that [GHC doesn't have a proper order of evaluation for type families](https://ghc.haskell.org/trac/ghc/ticket/11113), so a type family like `If` will happen to evaluate both of its arguments strictly. Ultimately, this is GHC's problem in the end, so I'm afraid there's simply no way to achieve what you're trying to accomplish at the moment with the `If` type family.

**Comment by odr** [comment]
You didn't understand me.
I suggest "that *boolean operations* must be also lazy".

In `singletons` `if` is correct but `&&` and `||` check both argument. That is a problem.

**Comment by RyanGlScott** [comment]
What I said about `If` applies equally to all type families in GHC. Since you mentioned `(&&)`, let's look at [its definition](https://hackage.haskell.org/package/base-4.10.1.0/docs/src/Data.Type.Bool.html#%26%26):

```haskell
type family a && b where
  'False && a      = 'False
  'True  && a      = a
  a      && 'False = 'False
  a      && 'True  = a
  a      && a      = a
```

If type families had a lazy semantics, then `(&&)` would short-circuit whenever its first argument evaluates to `False`. But alas, type families do not have this semantics, so the first equation will evaluate both arguments before computing the result.

**Comment by odr** [comment]
OK, I understand it. But I said not about that.

Type families have strict semantics. And it applies both for `If` and `&&`. OK.
In `Singletons.TH` `if` is (probably) translated to `case` with lazy semantics. It is a good thing because we can translate famous functions from `base` to `singletons` with a little difference.
But for `&&` the situation is worse. There is a common pattern to write `(<simple predicate> && <complex predicate>)`. To translate it to type level we have to write `if p1 then True else p2` instead of `p1 && p2`. It is undesirable.

To correct this we could define `&&` in `singletons` like this
```Haskell
singletons [d|
  a && b = if a then True else b
 |]
```
But maybe also possible translate all multi-definition of function not to normal type family but to case? I think that this is closer to regular Haskell behavior. I.e. translate code
```
f p11 ... pn1 =  ...
...
f p1k ... pnk = ...
```
to
```
f x1 ... xn = 
  case (x1,...,xn) of
     (p11,...,pn1) -> ...
     ...
     (p1k,...,pnk) -> ...
```

**Comment by RyanGlScott** [comment]
> In `Singletons.TH` `if` is (probably) translated to `case` with lazy semantics.

`singletons` does desugar `if x then y else z` into `case x of { True -> y; False -> z }`. This works in simple examples, such as your `testIf` function, where `y` and `z` aren't demanded anywhere else. Things start to fall over when this assumption doesn't hold, such as when we promote `f x y z = if x then y else z`:

```haskell
λ> ; $(promote [d| f x y z = if x then y else z |])
<interactive>:84:5-47: Splicing declarations
    promote
      [d| f_aspS x_aspT y_aspU z_aspV
            = if x_aspT then y_aspU else z_aspV |]
  ======>
    f_asqw x_asqx y_asqy z_asqz = if x_asqx then y_asqy else z_asqz
    type family Case_6989586621679119090_asqT x_asqP y_asqQ z_asqR t_asqU where
      Case_6989586621679119090_asqT x_asqP y_asqQ z_asqR True = y_asqQ
      Case_6989586621679119090_asqT x_asqP y_asqQ z_asqR False = z_asqR
    type FSym3 t_asqA t_asqB t_asqC = F t_asqA t_asqB t_asqC
    instance SuppressUnusedWarnings FSym2 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) FSym2KindInference) GHC.Tuple.())
    data FSym2 l_asqE l_asqF l_asqD
      = forall arg_asqG. SameKind (Apply (FSym2 l_asqE l_asqF) arg_asqG) (FSym3 l_asqE l_asqF arg_asqG) =>
        FSym2KindInference
    type instance Apply (FSym2 l_asqE l_asqF) l_asqD = F l_asqE l_asqF l_asqD
    instance SuppressUnusedWarnings FSym1 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) FSym1KindInference) GHC.Tuple.())
    data FSym1 l_asqI l_asqH
      = forall arg_asqJ. SameKind (Apply (FSym1 l_asqI) arg_asqJ) (FSym2 l_asqI arg_asqJ) =>
        FSym1KindInference
    type instance Apply (FSym1 l_asqI) l_asqH = FSym2 l_asqI l_asqH
    instance SuppressUnusedWarnings FSym0 where
      suppressUnusedWarnings _
        = snd ((GHC.Tuple.(,) FSym0KindInference) GHC.Tuple.())
    data FSym0 l_asqK
      = forall arg_asqL. SameKind (Apply FSym0 arg_asqL) (FSym1 arg_asqL) =>
        FSym0KindInference
    type instance Apply FSym0 l_asqK = FSym1 l_asqK
    type family F a_asqM a_asqN a_asqO where
      F x_asqP y_asqQ z_asqR = Case_6989586621679119090_asqT x_asqP y_asqQ z_asqR x_asqP
```

These are the important bits (which I've cleaned up a bit for readability):

```
    type family F x y z where
      F x y z = Case x y z x
    type family Case x y z t where
      Case x y z True = y
      Case x y z False = z
```

Here, `Case` is demanding all of its arguments due to the evaluation order of type families, so we're forced to evaulate both branches before returning a result.

The same reasoning explains why defining `(&&)` as `a && b = if a then True else b` won't make a difference in the compilation time of `TestAnd 1000`, since `n <= 0 && testAnd (n-1)` will still desugar into something like `Case (n <= 0) (testAnd (n-1))`, which will always evaluate `testAnd (n-1)`.

You might be thinking, "but why not just convert all occurrences of `a && b` to `if a then True else b`? That would be possible, but it would be completely ad hoc, as:

1. If users wanted to promote their own `(&&)` function, it wouldn't benefit from this transformation.
2. By the very nature of special-casing, we'd always leave out some class of functions that need to be lazy in its arguments. (This is a pretty large class in Haskell!)

-----

This is really GHC's fault in the end. I'd much rather pursue a solution that makes type family semantics behave sanely than attempt to mangle `singletons` to work around the issue.
