### ISSUE TITLE
Question about the kind of type-level functions

### ISSUE THREAD

**Issue by Lysxia** [goldfirere/singletons#320]
Why is the kind `a ~> b` of type-level functions `TyFun a b -> *` rather than `a -> b -> *`? Is it so that the symbol is less likely to be accidentally applied since it's more difficult to construct a type expression of kind `TyFun a b`?

**Comment by RyanGlScott** [comment]
As you've observed, the actual choice of datatype (`TyFun`, `(->)`, whatever) isn't of terrible importance. The important part is that you have something of kind `X a b -> *` (for some data type `X`) so that you can create as many defunctionalization data types with that kind as you want.

That being said, there is a little bit of history behind the choice of `TyFun`. As explained in Section 4.3.1 of [_Promoting Functions to Type Families in Haskell_](https://cs.brynmawr.edu/%7Erae/papers/2014/promotion/promotion.pdf), this feature of `singletons` was created before the advent of `TypeInType`, which is what makes it possible to use `(~>)` as a kind synonym. As a result, `singletons` used to have to manually inline `X a b -> *` everywhere as a workaround. I can imagine that using `TyFun` for `X` made it easier to identify uses of defunctionalization symbols than using `(->)` would have, as the latter could be easily confused for a normal data type's kind.

(Indeed, this is still somewhat the case today, since GHCi often expands `a ~> b` into `TyFun a b -> Type` in error messages and the like.)

**Comment by RyanGlScott** [comment]
I hope this adequately answers your question, @Lysxia. I'll optimistically assume so and close this (as it's not really an issue _per se_). Please reopen if you disagree.
