### ISSUE TITLE
Impossible: reification returned a bogus instance

### ISSUE THREAD

**Issue by LeanderK** [goldfirere/singletons#345]
My code:

```haskell
import Data.Singletons.TH
import Data.Singletons
import Data.Singletons.Prelude
import GHC.Types

data OneShape :: Type -> Nat -> Type where
    OneNil :: OneShape a 0
    OneCons :: a -> OneShape a x -> OneShape a (x + 1)

$(genSingletons [''OneShape])
```

produces:
```
    Impossible: reification returned a bogus instance
   |
34 | $(genSingletons [''OneShape])
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
```

I am using: singletons 2.4.1

I not sure what happened there....

**Comment by RyanGlScott** [comment]
This is really an issue with `th-desugar`'s `expandType` function, which `singletons` uses under the hood. Here's a simpler reproduction of this issue that only depends on `expandType`:

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE PolyKinds #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE UndecidableInstances #-}
module Bug where

import GHC.TypeNats
import Language.Haskell.TH
import Language.Haskell.TH.Desugar

type Two = Succ 1
type family Succ (x :: k) :: k
type instance Succ (z :: Nat) = z + 1

$(return [])

test :: String
test =
  $(expandType (DConT ''Two) >>= stringE . show)
```

```
$ /opt/ghc/8.4.3/bin/ghci Bug.hs
GHCi, version 8.4.3: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/rgscott/.ghci
[1 of 1] Compiling Bug              ( Bug.hs, interpreted )

Bug.hs:21:5: error:
    • Impossible: reification returned a bogus instance
    • In the untyped splice:
        $(expandType (DConT ''Two) >>= stringE . show)
   |
21 |   $(expandType (DConT ''Two) >>= stringE . show)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

What is going here? When `th-desugar` expands type synonyms, it also makes an effort to expand type family instances as well. So it first expands `Two` to `Succ 1`, and then attempts to expand `Succ 1` using the type family instance for `Succ`.

However, when attempting to substitute into the RHS of `Succ`'s instance, `th-desugar` tries to match the following two types:

* `(z :: Nat)`
* `1`

However, because of [these lines of code](https://github.com/goldfirere/th-desugar/blob/37ea11115f3b8eb05a7322eb78cc271f4dbfe6b7/Language/Haskell/TH/Desugar/Subst.hs#L122-L125):

```haskell
matchTy ign (DSigT ty _ki) arg = case ign of
  YesIgnore -> matchTy ign ty arg
  NoIgnore  -> Nothing
  -- but we can safely ignore kind signatures on the target
```

Because `expandType` uses `NoIgnore`, it gives up when it encounters the kind signature on `z`. As a result, we get no substitution (i.e., `Nothing`) back in [these lines of code](https://github.com/goldfirere/th-desugar/blob/37ea11115f3b8eb05a7322eb78cc271f4dbfe6b7/Language/Haskell/TH/Desugar/Expand.hs#L130-L134):

```haskell
            case dinsts of
              [DTySynInstD _n (DTySynEqn lhs rhs)] -> do
                subst <-
                  expectJustM "Impossible: reification returned a bogus instance" $
                  unionMaybeSubsts $ zipWith (matchTy ign) lhs syn_args
```

Which causes `th-desugar` to panic.

I'm not sure how to proceed here. Perhaps if we receive `Nothing` back here, we should simply give up on expanding type family instances. What are your thoughts, @goldfirere?

**Comment by LeanderK** [comment]
hijacking this question a bit, but it seems to me that the limitation is purely in `th-desugar`. It's a small, but important, piece of code and I would now roll up my sleeves and write the instances simply by hand. Are there any examples in the `singletons` for the handwritten instances and definitions?

**Comment by RyanGlScott** [comment]
> Are there any examples in the `singletons` for the handwritten instances and definitions?

Certainly. The [`ByHand`](https://github.com/goldfirere/singletons/blob/c776637d11055ac1c47ddf7e96c7ed9067687041/tests/ByHand.hs) and [`ByHand2`](https://github.com/goldfirere/singletons/blob/c776637d11055ac1c47ddf7e96c7ed9067687041/tests/ByHand2.hs) test cases are dedicated entirely to doing this.

Fair warning: singling GADTs tends to be a fair deal trickier than singling normal ADTs, but it's often possible. In your particular example, however, you'll need to use GHC 8.6 in order to make things typecheck, since an important kind-checking patch is present in 8.6 but not 8.4 that makes the whole thing work. This is the code you'd want to use:

```haskell
data instance Sing :: forall a x. OneShape a x -> Type where
    SOneNil  :: Sing OneNil
    SOneCons :: Sing y -> Sing ys -> Sing (OneCons y ys)

instance SingKind a => SingKind (OneShape a x) where
  type Demote (OneShape a x) = OneShape (Demote a) x
  fromSing SOneNil           = OneNil
  fromSing (SOneCons sy sys) = OneCons (fromSing sy) (fromSing sys)
  toSing OneNil         = SomeSing SOneNil
  -- The lines below in particular requires GHC 8.6 in order to typecheck.
  toSing (OneCons y ys) = withSomeSing y  $ \sy  ->
                          withSomeSing ys $ \sys ->
                          SomeSing $ SOneCons sy sys
```

**Comment by LeanderK** [comment]
`unsafeCoerce` seems to be working...this deserves a big, fat `FIXME` so that it doesn't stay long
I am unable to use `8.6` yet

**Comment by RyanGlScott** [comment]
Sounds good to me. In that case, I'm going to migrate this issue over to `th-desugar` at goldfirere/th-desugar#83 .
