### ISSUE TITLE
singletons-2.5.1 won't build on Windows

### ISSUE THREAD

**Issue by crockeea** [goldfirere/singletons#384]
I let stack try to build singletons-2.5.1 on Windows 10 for over two hours before giving up. It compiles in a perfectly reasonable amount of time on Unix.

The build hang occurs on `Data.Singletons.Prelude.Instances`.

**Comment by RyanGlScott** [comment]
What GHC version are you using?

**Comment by crockeea** [comment]
GHC-8.6.3

**Comment by RyanGlScott** [comment]
GHC 8.6.3 in particular is completely broken with respect to Template Haskell, unfortunately. Due to [GHC Trac #16057](https://ghc.haskell.org/trac/ghc/ticket/16057), any attempt to use a Template Haskell splice will cause GHC to infintely loop.

There should be an upcoming GHC 8.6.4 release to address this, but until then, the only course of action that I can recommend is downgrading to GHC 8.6.2.

**Comment by crockeea** [comment]
Okay, good to know!
