### ISSUE TITLE
Generic existential wrapper / conversion function

### ISSUE THREAD

**Issue by epoberezkin** [goldfirere/singletons#461]
Ryan, Richard - thanks for singletons!

Maybe I missed it, but I could not find some generic existential wrapper to the parametrised type to be used with singleton types - something similar to generic Some in parameterized-utils, but with additional singleton in the type.

If it's not somewhere in the library already, could these be added into, say, Data.Singleton.Some, or somewhere else?

```haskell
data Some :: (k -> Type) -> Type where
  Some :: Sing p -> t p -> Some t

some :: SingI p => t p -> Some t
some = Some Sing
```

See this comment here: https://blog.jle.im/entry/introduction-to-singletons-2.html#comment-4901173716 for some context.

I could make a PR if it sounds ok.

**Comment by RyanGlScott** [comment]
Your `Some` sounds very much like [`Sigma`](https://hackage.haskell.org/package/singletons-2.7/docs/src/Data.Singletons.Sigma.html#Sigma) from `Data.Singletons.Sigma`. Is that what you are looking for?

**Comment by epoberezkin** [comment]
Indeed, just looks simpler (without TyCon), and reads like what it means... `Some Thing` as a wrapped or `Thing p` type and `some` function to wrap value of any of `Thing p` types...

Thanks.

**Comment by RyanGlScott** [comment]
It's true that `Some` is simpler. But that's because `Sigma` was intended for more sophisticated examples. Put another way, your `Some` is `DSum Sing`, where [`DSum`](http://hackage.haskell.org/package/dependent-sum-0.7.1.0/docs/Data-Dependent-Sum.html#t:DSum) is taken from the `dependent-sum` package. Because `Some` only works for type parameters of kind `k -> Type`, there are certain dependent-sum-like constructions that simply aren't possible with `Some`. For instance, you couldn't say `Some NotSym0`, since `NotSym0` doesn't have the right kind, but you can say `Sigma Bool NotSym0`.

**Comment by epoberezkin** [comment]
Cool, thanks - I will check it. Should I close here?

**Comment by RyanGlScott** [comment]
As you have observed, you can take any use case for `DSum Sing` and adapt it to `Sigma` by using `TyCon` where necessary. Whether you find one more pleasant to use than the other is a matter of personal taste.

**Comment by RyanGlScott** [comment]
> Should I close here?

Yes, I think that would be best.
