### ISSUE TITLE
Pattern matching specific Nat singletons

### ISSUE THREAD

**Issue by epoberezkin** [goldfirere/singletons#472]
I am trying to define the function on Nat singleton where the result type depends on the type of the argument.

For example, I have:

```haskell
type family T (n :: Nat) :: Nat where
  T 1 = 1
  T 2 = 1
  T n = n
```

Is it possible in any way to create this function:

```
sT :: Sing (n :: Nat) -> Sing (T n)
```

Or is it impossible and that's why such functions do not "singletonize"? The library says it is unsupported, but possibly it is not the limitation of the library, but of the compiler?

**Comment by RyanGlScott** [comment]
There are two ways to interpret your question. I'll try to answer both:

1. Given a type family, can `singletons` automatically produce the corresponding singled definition?

   The answer to this question is "no". `singletons` only supports taking a term-level definition and creating a singled definition out of that. Put another way, you can't take an arbitrary `type family T` and create `sT` from it. You can, however, take a term-level `t` and use it to create `T` and `sT`.
2. Will this function single successfully?

   ```hs
   $(singletonsOnly [d|
     t :: Nat -> Nat
     t 1 = 1
     t 2 = 1
     t n = n
     |])
   ```

   The answer to this question is "no". At least, not with the way it's written above. `singletons` will simply refuse to process that definition:

   ```
   error: Singling of literal patterns not yet supported
      |
      | $(singletonsOnly [d|
      |   ^^^^^^^^^^^^^^^^^^...
   
   error: Q monad failure
      |
      | $(singletonsOnly [d|
      |   ^^^^^^^^^^^^^^^^^^...
   ```

   You can, however, rewrite this to avoid the use of literal patterns. For example, this will single successfully:

   ```hs
   $(singletonsOnly [d|
     t :: Nat -> Nat
     t n = if      n == 1 then 1
           else if n == 2 then 1
           else                n
     |])
   ```

   This limitation of `singletons` is somewhat fundamental to the way GHC's typechecker currently works. If you define `T` like this:

   ```hs
   type family T (n :: Nat) :: Nat where
     T 1 = 1
     T 2 = 1
     T n = n
   ```

   Then the third equation of `T` will only reduce if GHC can be sure that the argument to `T` is not `1` or `2`. In GHC jargon, the argument must be _apart_ from what the previous equations match on. However, `SNat` (the singleton type for `Nat`s) isn't really equipped for defining this sort of function. You could use `SNat` to define the first two equations at the least:

   ```hs
   sT :: forall (n :: Nat). Sing n -> Sing (T n)
   sT SNat
     | Just Refl <- sameNat (Proxy @n) (Proxy @1) = SNat @1
     | Just Refl <- sameNat (Proxy @n) (Proxy @2) = SNat @1
   ```

   However, there is no good way to define the third equation. You might think to try this:

   ```hs
   sT :: forall (n :: Nat). Sing n -> Sing (T n)
   sT sn@SNat
     | Just Refl <- sameNat (Proxy @n) (Proxy @1) = SNat @1
     | Just Refl <- sameNat (Proxy @n) (Proxy @2) = SNat @1
     | otherwise                                  = sn
   ```

   However, that won't typecheck:

   ```
   error:
       • Couldn't match type ‘n’ with ‘T n’
         ‘n’ is a rigid type variable bound by
           the type signature for:
             sT :: forall (n :: Nat). Sing n -> Sing (T n)
         Expected type: Sing (T n)
           Actual type: Sing n
   ```

   The problem is that within the `otherwise` case, there is no way for GHC to know that `n` is apart from `1` and `2`. As a result, `T n` cannot reduce to `n` (the third equation of `T`), which is why the error message says that it cannot match `n` with `T n`.

   (Note that the variant of `t` I suggest above with two `if` expressions does not suffer from this problem because it does not match on a `Nat`, but rather the results of the expressions `n == 1` and `n == 2`. This is a subtle but important distinction, because it is possible to exhaustively enumerate all possible cases in this version of `t`. On the other hand, you cannot exhaustively enumerate all possible `Nat`s.)

   You may feel that this is a bit silly. After all, why _shouldn't_ GHC be able to conclude that `n` is apart from `1` and `2` in the `otherwise` case? If GHC had some sort of first-class notion of apartness, perhaps we could communicate this fact to the typechecker. But alas, we do not. That being said, if you're feeling _really_ bold, you might opt for a slightly... adventurous way to work around this issue:

   ```hs
   sT :: forall (n :: Nat). Sing n -> Sing (T n)
   sT sn@SNat
     | Just Refl <- sameNat (Proxy @n) (Proxy @1) = SNat @1
     | Just Refl <- sameNat (Proxy @n) (Proxy @2) = SNat @1
     | otherwise                                  = unsafeCoerce sn
   ```

   I know, I know. While I wouldn't normally recommend using `unsafeCoerce`, this might be the only way of making this actually work (short of rewriting `t` like I suggested above). If it makes you feel better, the `singletons` library itself [uses this trick in various places](https://github.com/goldfirere/singletons/blob/9da673b0de87e602bb43389d505f07f702d05bc5/singletons-base/src/GHC/TypeLits/Singletons/Internal.hs#L117). Just make sure to use `unsafeCoerce` responsibly if you do go down this route.

**Comment by epoberezkin** [comment]
@RyanGlScott thank you very much - this is super helpful.

I was actually trying to ask the question 3 - given that pattern matching on Nats doesn't work, as it doesn't single, is there a way to work around it - but you answered it. The option with "if" is perfect - it produces both the type family and the singled function. The second approach can be useful some other time - I couldn't figure out a way to pattern-match on SNats.

Thank you!
