### ISSUE TITLE
Is it possible to break up `singletons` even more?

### ISSUE THREAD

**Issue by masaeedu** [goldfirere/singletons#495]
Hello there. I am a big fan of the change from #420 in which singletons was broken up into several smaller libraries. This will probably come as a very annoying request on the heels of that change, but I would like to ask that it be broken up further still.

The reason is primarily didactic. Opening the haddock for Data.Singletons is an intimidating experience. Within a few lines of seeing `type family Sing`, the user is greeted with things like this:

![image](https://user-images.githubusercontent.com/3674056/115330044-da95c180-a182-11eb-84fc-f8c617933661.png)

![image](https://user-images.githubusercontent.com/3674056/115330071-e5e8ed00-a182-11eb-8dc1-961133655bf2.png)

![image](https://user-images.githubusercontent.com/3674056/115330112-f7ca9000-a182-11eb-8f8f-9565fc68b2d1.png)

Personally I need a little bit more handholding/encouragement in the way of the singleton before I can care about what `SLambda`, `applySing` `~>` etc. are. Is it possible to extract a short, punchy `Data.Singletons.Core` that defines only the minimal definitions required to state and (if necessary, laboriously) work with the singletons pattern? This would entail removing the utilities for:

- defunctionalization
- pattern synonyms
- converting between implicit/explicit passing
- "meta-singletons"

As things stand these things somewhat drown out the essence of the library. IMO it would be much preferable to drown the core definitions in documentation and handwritten examples.

By quantity, the defunctionalization stuff seems to be the primary culprit. If possible, can all the defunctionalization stuff be moved entirely out of `singletons` into a new, singletons-agnostic dependency? If that's not feasible, at least out of the `Data.Singletons` module?

One motivation for moving it into a separate library is that Haskell's lack of partial application is not a problem faced exclusively by `singletons` users. Even if you're using type-level Haskell as a mere simply-typed lambda calculus (no dependent quantification, no polykinds even), you end up feeling the lack of first class functions acutely. So a high quality, singletons-agnostic library for using the defunctionalization trick at the type level would be useful in many contexts. It would for example scratch the same itch as the [`first-class-families`](https://hackage.haskell.org/package/first-class-families) package.

**Comment by int-index** [comment]
> The reason is primarily didactic.

Then this is probably better served by more organized and welcoming documentation. For example, Haddock sections could be used to organize definitions into groups, so that defunctionalization and singletonization are presented separately. And core definitions such as `Sing` and `SingI` would benefit from example usages in their documentation.

**Comment by RyanGlScott** [comment]
Thanks for the bug report! Coming up with documentation that suits the needs of all users is a challenging thing, and I definitely agree that more could be done to make the documentation more accessible to people who aren't `singletons` experts.

I think there are two similar but distinct issues being discussed:

1. `Data.Singletons` is in desperate need of more examples in its Haddocks. I think one reason why things are the way they are currently is because most of the documentation effort has been focused on [the README](https://github.com/goldfirere/singletons/blob/70d622645b960d60411ab8f31d16ffb91e69379e/README.md), which provides a more "tutorial-like" introduction to `singletons` and related libraries. That being said, I recognize that the `README` is not as discoverable as the Haddocks, and its style of prose may not work well for all users.

   I'd gladly welcome a PR which adds more Haddock examples to entities in `Data.Singletons`. Indeed, it might even suffice to move some of the information from the `README` over to the Haddocks, updating the `README` to link to the Haddocks instead. I'm open to suggestions on the best way to consolidate this information.

2. The organization of the `Data.Singletons` module leaves much to be desired. For what it's worth, the way `Data.Singletons` looks right now isn't really the result of deliberate planning, but rather the result of `Data.Singletons` slowly gaining new features over time. Admittedly, not much thought has been put into the best way to organize all of these features, and I'm open to the idea of shuffling the order around to present things more coherently.

   I do think `singletons` would benefit from having a single module that exports what `Data.Singletons` does currently, as the combination of `Sing`, `SingKind`, `SingI`, etc. plus defunctionalization symbols is a common use case. However, I'd be open to having smaller modules that only expose small cross-sections of `Data.Singletons`, especially if that would streamline the usage of `singletons` for certain use cases. For example, we might advise users to import, say, `Data.Singletons.Defun` if they only care about defunctionalizing type families.

   Personally, I'm not convinced that we should split off the defunctionalization-related aspects of `singletons` into a separate _library_, as I think the same objective would be better served (and with less package churn) by the reorganizing the modules. I would be willing to change my mind if enough users express a desire for this, however.

**Comment by goldfirere** [comment]
I tend to agree with @int-index and @RyanGlScott in that this is a good issue to fix, but that the fix isn't necessarily further splitting, but instead better documentation / sign-posting.

**Comment by masaeedu** [comment]
I think the consensus from the three comments so far is that the defunctionalization code should not be moved out of this library (regardless of whether it is technically feasible to do so).

Is the consensus also that it shouldn't be moved into a separate module? If so I can close this issue, a general purpose issue for improving documentation is probably best managed separately.

**Comment by RyanGlScott** [comment]
> Is the consensus also that it shouldn't be moved into a separate module?

That's my understanding yes.

> If so I can close this issue, a general purpose issue for improving documentation is probably best managed separately.

If you want to open a new issue, that's fine with me. Otherwise, I'd be fine with repurposing this issue to be the thing that tracks improving the documentation in `Data.Singletons`.
