### ISSUE TITLE
Can singletons deal with unsaturated constructors

### ISSUE THREAD

**Issue by expipiplus1** [goldfirere/singletons#498]
Take the following code:

```haskell
$(singletons [d|
  data Tree a
    = Leaf a
    | Branch [Tree a] a

  prepend :: Tree a -> Tree a -> a -> Tree a
  prepend (Leaf a) (Branch xs n) = Branch (Leaf a : xs)
  ...
  |])
```

I'd like to generate the type family (and all the accoutrements) like:

```haskell
type family Prepend a b where
  Prepend (Leaf a) (Branch xs n) = Branch (Leaf a ': xs)
  ...
```

i.e. the type family can be used without supplying the final `a` argument. 

Is this at all possible? Sadly singletons runs into issues if I try to wrap `a -> Tree a` in a newtype or anything fancy like that.

**Comment by RyanGlScott** [comment]
Just to make sure I understand what you're asking for, I think you're actually requesting that `singletons-th` do two things:

1. Generate a `Prepend` type family with only two visible arguments, and
2. Make the kind of `Prepend` be `Tree a -> Tree a -> a -> Tree a`.

I wanted to call out the second requirement since my first inclination was to try promoting `prepend` with its top-level signature. That is:

```hs
$(singletons [d|
  ...
  -- prepend :: Tree a -> Tree a -> a -> Tree a
  prepend (Leaf a) (Branch xs n) = Branch (Leaf a : xs)
  ...
  |])
```

That gets you very close to what you want, since the following type family will be generated:

```hs
type family Prepend a_aokU a_aokV where
  Prepend (Leaf_aokF a_aokX) (Branch_aokG xs_aokY n_aokZ) = Apply BranchSym0 (Apply (Apply (:@#@$) (Apply LeafSym0 a_aokX)) xs_aokY)
```

While this meets requirement (1), it doesn't meet requirement (2), as GHCi reports that the kind of `Prepend` is:

```
> :k Prepend
Prepend :: Tree a -> Tree a -> a ~> Tree a
```

The `a ~> Tree a` bit means that you won't be able to use a partial application of `Prepend t1 t2` without use of the `Apply` type family. Again, I'm making an assumption that this isn't what you wanted, because otherwise you could just make use of `Prepend`'s defunctionalization symbols.

Unfortunately, I can't think of a workaround to make `singletons` do what you want—not yet, anyways. In the general case, `singletons` absolutely must eta expand promoted definitions in order to ensure that all type family applications are applied to an appropriate number of arguments. If you had defined `prepend` this way, for instance:

```hs
branch2 :: [Tree a] -> a -> Tree a
branch2 t x = Branch t x

prepend :: Tree a -> Tree a -> a -> Tree a
prepend (Leaf a) (Branch xs n) = branch2 (Leaf a : xs)
```

Then it would be incorrect to promote `prepend` to `Prepend (Leaf a) (Branch xs n) = Branch2 (Leaf a ': xs)`, since the `Branch2` type family would need to be applied to two visible arguments in order to be well formed.

I suppose one could imagine some sort of custom option that allows fine-tuning how eta expansion works in `singletons`, but it's far from clear to me what the API for that would look like. `singletons-th` makes a _lot_ of assumptions about things being eta expanded in various places, after all.

All of this makes me wish that we had [unsaturated type families](https://github.com/ghc-proposals/ghc-proposals/blob/79f48248ae31b1a490deb1b019c206efa0be89da/proposals/0242-unsaturated-type-families.rst). If we had them, we wouldn't need need to defunctionalize anything in `singletons-th`, and we could likely avoid the use of eta expansion as a consequence.

**Comment by expipiplus1** [comment]
Yes! Your assumptions were all correct and response very comprehensible. Thank you for taking the time to write such a generous response.

I don't think I have much more to add or question :D. I'll leave it to you to close or not.

Thanks again!

**Comment by RyanGlScott** [comment]
Alright, I'll close this. I'll add this to my "revisit-this-when-GHC-gets-unsaturated-type-families" list :)
