### ISSUE TITLE
Introduce `SingI1`, a second-order version of `SingI`

### ISSUE THREAD

**Issue by DanielRrr** [goldfirere/singletons#500]
We were replacing `Typeable` with`SingI` in our project. We realised that having `SingI` is not enough in several places since we also need `SingI` for type constructors. So we introduced the class `SingI1` for lifting `SingI` to unary constructors in the same fashion as, for example, `Eq1` or `Ord1`.

```haskell
class SingI1 f where
  withSingI1 :: forall x r. SingI x => (SingI (f x) => r) -> r
```

The idea is to introduce this type class in the library.

**Comment by DanielRrr** [comment]
Here is our example in more detail.
Consider the `mapImpl` function.
```haskell
mapImpl
  :: forall c rs .
    ( MapOp c
    , WellTyped (MapOpInp c)
    , Typeable (MapOpRes c)
    )
  => ([TypeCheckedOp] -> TypeCheckedInstr)
  -> Notes (MapOpInp c)
  -> U.ExpandedInstr
  -> [U.ExpandedOp]
  -> HST (c ': rs)
  -> (forall v' . (KnownT v') =>
        Notes v' -> HST rs -> TypeCheckInstr (HST (MapOpRes c v' ': rs)))
  -> TypeCheckInstrNoExcept (TypeCheckedSeq (c ': rs))
mapImpl cons vn instr mp i@(_ ::& rs) mkRes = do
  preserving (tcList mp ((vn, Dict, def) ::& rs)) cons $ \(_ :/ subp) ->
    case subp of
      sub ::: subo ->
        case subo of
          (bn, _, _bvn) ::& rs' -> do
            Refl <- onTypeCheckInstrErr instr (SomeHST i) (Just Iteration)
              $ eqHST rs rs'
            x <- mkRes bn rs'
            pure $ i :/ MAP sub ::: x
          _ -> typeCheckInstrErr instr (SomeHST i) (Just Iteration)
      AnyOutInstr _ ->
        typeCheckInstrErr' instr (SomeHST i) (Just Iteration) CodeAlwaysFails
```
where (here `T` is an inductive ADT):
```haskell
class MapOp (c :: T) where
  type MapOpInp c :: T
  type MapOpRes c :: T -> T
  mapOpToList :: Value' instr c -> [Value' instr (MapOpInp c)]
  mapOpFromList
    :: (KnownT b)
    => Value' instr c -> [Value' instr b] -> Value' instr (MapOpRes c b)
  mapOpNotes :: Notes c -> Notes (MapOpInp c)
```
We were trying to replace `Typeable (MapOpRes c)` with `forall x. SingI (MapOpRes c x)` using `QuantifiedConstraints`, but we encountered the `Illegal application` error. The `SingI1` class solves this problem, and `mapImpl` with the constraints below is well-typed now (if we use `withSingI1` properly ofc):
```haskell
mapImpl
  :: forall c rs.
    ( MapOp c
    , WellTyped (MapOpInp c)
    , SingI1 (MapOpRes c)
    )
```

**Comment by DanielRrr** [comment]
BTW, I guess we need the 'enhancement' flag here

**Comment by RyanGlScott** [comment]
Thanks for providing an example, as I was wondering if something like `type SingI1 f = forall x. SingI x => SingI (f x)` would suffice for your use case. It turns out the answer is "no", since you want to instantiate `f` to be a type family.

Some various thoughts and questions:

* Given that we autogenerate `SingI` instances with Template Haskell, we should probably autogenerate them for `SingI1` as well. I don't foresee any fundamental difficulties with doing so—we'd just have to make sure _not_ to generate `SingI1` instances for things like `True`, which don't have the right kind.
* If `SingI1` is to `SingI` as `Eq1` is to `Eq`, then I wonder if we should also have `SingI2` to mirror `Eq2`.
* Drawing upon the `Eq1` analogy, the type of `withSingI` isn't quite what I would expect. I was expecting something closer to what `Eq1`/`Ord1`/etc. do, which is provide a way to lift a `sing :: Sing a` function to a higher-order type constructor. That it, something like:

  ```hs
  class SingI1 f where
    liftSing :: Sing x -> Sing (f x)
  ```

  Note that your `withSingI1` can be defined in terms of this class:
  
  ```hs
  sing1 :: (SingI1 f, SingI x) => Sing (f x)
  sing1 = liftSing sing
  
  withSingI1 :: forall f x r. (SingI1 f, SingI x) => (SingI (f x) => r) -> r
  withSingI1 k = withSingI (sing1 @f @x) k
  ```
* Drawing upon the `Eq1` analogy even further, I wonder if we should give `SingI1` a quantified superclass in the spirit of [this MR](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4727):

  ```hs
  class (forall x. SingI x => SingI (f x)) => SingI1 f where
    liftSing :: Sing x -> Sing (f x)
  ```
  
  I don't foresee any unfortunate interactions with type families by doing so. At the very least, this simple example typechecks with this superclass:
  
  ```hs
  type family F (x :: Type) :: Type -> Type
  
  f :: forall x y. (SingI1 (F x), SingI y) => Proxy x -> Sing (F x y)
  f _ = sing1 @(F x) @y
  ```

**Comment by DanielRrr** [comment]
Your idea makes sense, I would solve this issue in that way. Why don't we make a kind of implementation plan or something?

**Comment by DanielRrr** [comment]
> I wonder if we should also have SingI2 to mirror Eq2.

Do you mean something like that?
```haskell
class (forall x y. (SingI x, SingI y) => SingI (f x y)) => SingI2 f where
  liftSing2 :: Sing x -> Sing y -> Sing (f x y)
```

**Comment by DanielRrr** [comment]
I think we also may introduce similar functions for `SingI2`, for example:

```haskell
sing2 :: (SingI2 f, SingI x, SingI y) => Sing (f x y)
sing2 = liftSing2 sing sing

withSingI2 :: forall f x y r. (SingI2 f, SingI x, SingI y) => (SingI (f x y) => r) -> r
withSingI2 k = withSingI (sing2 @f @x @y) k
```

**Comment by RyanGlScott** [comment]
For the record, I'm working on this in the [`T500`](https://github.com/goldfirere/singletons/tree/T500) branch. (I didn't notice your own fork until after I had pushed it—sorry!) The work is nearly done; I just need to add some more documentation to the new API additions.

One thing I'm unclear on is what type to give to the `SingI{1,2}` counterparts to the [`withSingI`](https://hackage.haskell.org/package/singletons-3.0/docs/Data-Singletons.html#v:withSingI) function. (Not to be confused with your proposed `withSingI{1,2}` functions, which I'll address in a bit.) My first inclination was to write this:

```hs
withSingI1 :: Sing (f x) -> (SingI1 f => r) -> r
```

But this actually doesn't work, since the internals of `withSingI` rely on `unsafeCoerce`-ing a class dictionary to work. You would actually need something closer to this:

```hs
withSingI1 :: (forall x. Sing x -> Sing (f x)) -> (SingI1 f => r) -> r
```

There are two more problems that arise from this version of `withSingI`:

1. Would anyone actually find this function useful?
2. More critically, the superclass constraint for `SingI1` would prevent the `unsafeCoerce` trick from working, since it would mean that a `SingI1` dictionary is no longer a newtype. Argh.

In light of (1), I'm wondering if we shouldn't even bother with defining these functions. The `withSingI{1,2}` functions that you propose do something quite different, after all: they (essentially) take a `(SingI1 f, SingI x)` constraint and turn it into a `SingI (f x)` constraint (and similarly for `(Sing2 f, SingI x, SingI y)`/`SingI (f x y)`). These are useful in their own right, but I'd advocate for naming them something different, as the `withSingI` function has a different purpose—namely, converting an explicit singleton into an implicit one. Your proposed functions convert a collection of implicit singleton constraints into a different form, so perhaps they should be named something else. `usingSing{1,2}`, maybe?

**Comment by DanielRrr** [comment]
> I didn't notice your own fork until after I had pushed it—sorry! The work is nearly done; I just need to add some more documentation to the new API additions.

Oh, never mind, go ahead then.

> Would anyone actually find this function useful?

Hm, perhaps.

> the superclass constraint for SingI1 would prevent the unsafeCoerce trick from working, since it would mean that a SingI1 dictionary is no longer a newtype. 

Hm, I haven't thought about that. AFAIU, a possible solution might be quite tricky.

> usingSing{1,2}, maybe?

That's OK to me.

**Comment by RyanGlScott** [comment]
See #501.
