### ISSUE TITLE
Class for applying families

### ISSUE THREAD

**Issue by treeowl** [goldfirere/singletons#527]
I may well be missing some utility or idiom, but today I found myself looking for something like

```haskell
class WDS (sym :: j ~> k) where
  wds :: forall t. Sing t -> Sing (sym @@ t)
```

I couldn't find anything, so I rolled my own. Is there a Right Way to approach this? If not, should there be?

**Comment by RyanGlScott** [comment]
Does [`applySing`](https://hackage.haskell.org/package/singletons-3.0.1/docs/Data-Singletons.html#v:applySing) (or, if you like infix operators, [`(@@)`](https://hackage.haskell.org/package/singletons-3.0.1/docs/Data-Singletons.html#v:-64--64-)) give you what you seek?

**Comment by treeowl** [comment]
A partially applied `applySing` looks like what I need, yes, but how to I get from `f` to `SLambda f`? I don't actually understand the role of `SLambda` in the infrastructure here.

**Comment by RyanGlScott** [comment]
> I don't actually understand the role of SLambda in the infrastructure here.

Broadly speaking, `SLambda` is the singleton type for functions, just as `SBool` is the singleton type for `Bool`. Functions are treated a bit specially in `singletons`, which is why the actual definition of `SLambda` looks different from most singleton types, but it's really just a `Sing` function.

> A partially applied `applySing` looks like what I need, yes, but how to I get from `f` to `SLambda f`?

There are two ways of constructing an `SLambda` value:

1. With the `singFun*` family of combinators (e.g., [`singFun1`](https://hackage.haskell.org/package/singletons-3.0.1/docs/Data-Singletons.html#v:singFun1)). For example, if you have `sId :: Sing a -> Sing (Id a)`, then `singFun1 @IdSym0 sId :: SLambda IdSym0`, where `IdSym0 :: a ~> a` is the [defunctionalized](https://github.com/goldfirere/singletons/tree/489c1c8b685f36bdb9f1cbcbab52066009e044f8#promoting-functions) version of `Id`. 
2. Using the [`SingI`](https://hackage.haskell.org/package/singletons-3.0.1/docs/Data-Singletons.html#t:SingI) class. For example, `sing @IdSym0` is another way of constructing a value of type `SLambda IdSym0`. `singletons-th` automatically generates `SingI` instances for defunctionalization symbols such as `IdSym0`, which is why this technique works.

**Comment by treeowl** [comment]
Aha! So I just need to instantiate `SingI`! Thanks a lot. I wonder if the documentation could be expanded a bit to make that more clear.

**Comment by RyanGlScott** [comment]
Indeed, the documentation for `singletons` could always stand to be improved. Pull requests welcome!

**Comment by RyanGlScott** [comment]
I've attempted to explain this better in #544.
