### ISSUE TITLE
How does sCases work?

### ISSUE THREAD

**Issue by RobertFischer** [goldfirere/singletons#543]
I'm trying to use `sCases`, but I'm constantly getting "GHC stage restriction".  How would I use this function to generate an implementation of a function?

If there's some documentation or a good example blog post that I'm missing, please point me in that direction.

**Comment by RyanGlScott** [comment]
Indeed, the documentation for `sCases` (and [`cases`](https://hackage.haskell.org/package/singletons-th-3.1.1/docs/Data-Singletons-TH.html#v:cases), the function on which it is based) is rather lacking. A simple example of its use can be found [here](https://github.com/goldfirere/singletons/blob/70d622645b960d60411ab8f31d16ffb91e69379e/singletons-base/tests/compile-and-dump/Singletons/T124.hs). Suppose you have this:

```hs
module Singletons.T124 where

import Data.Singletons.TH
import Prelude.Singletons

$(singletons [d|
  foo :: Bool -> ()
  foo True = ()
  foo False = ()
  |])
```

And that you want to write a function of this type:

```hs
bar :: SBool b -> STuple0 (Foo b)
```

How would you do this? You might be tempted to write the following:

```hs
bar _ = STuple0
```

However, this won't typecheck, as `Foo b` won't reduce to `'()` unless GHC knows `b` is either `True` or `False`. In order to convince GHC of this, you must explicitly match on each of `SBool`'s data constructors:

```hs
bar :: SBool b -> STuple0 (Foo b)
bar b = case b of
  STrue  -> STuple0
  SFalse -> STuple0
```

This is doable, but somewhat tedious, and it only gets more tedious the more data constructors you have. For that reason, we offer `sCases` to generate this boilerplate code for you. The following is equivalent to the implementation of `bar` above:

```hs
bar :: SBool b -> STuple0 (Foo b)
bar b = $(sCases ''Bool [| b |] [| STuple0 |])
```

`cases` is a more general version of `sCases` that accepts any data type, not just singleton types. Note that `sCases ''Bool` is equivalent to `cases ''SBool`. (In a previous version of `singletons`, `cases` used to not be able to handle singleton types, which is why a separate `sCases` function was introduced. Nowadays, `sCases` mostly exists for historical reasons.)

**Comment by RyanGlScott** [comment]
I've added the explanation above to the Haddocks in #544.

**Comment by RobertFischer** [comment]
Thanks. That's super helpful.
