### ISSUE TITLE
Struggling to get even the most basic usage of Data.Singletons.TypeLits.Nat to compile

### ISSUE THREAD

**Issue by CRogers** [goldfirere/singletons#76]
Hi,

I'm trying to use `Nat` as exported by `Data.Singletons.TypeLits` on GHC 7.8.2 but can't get even the most basic piece of code to compile:

``` haskell
{-# LANGUAGE ScopedTypeVariables, TemplateHaskell, GADTs, DataKinds, TypeFamilies #-}

import Data.Singletons.TH
import Data.Singletons.TypeLits

singletons [d|
    data Foo = Bar Nat
 |]
```

Errors with:

```
Couldn't match type ‘Integer’ with ‘Nat’
Expected type: DemoteRep 'KProxy
  Actual type: Nat
In the first argument of ‘toSing’, namely ‘b_ayYo’
In the expression: toSing b_ayYo :: SomeSing (KProxy :: KProxy Nat)
```

If I use my own version of `Nat` instead (`data Nat = Z | S Nat`) it all works fine. Am I doing something wrong/misunderstanding something, or is the functionality not working as expected?

**Comment by nomeata** [comment]
It looks like the above recipie is out of date, I get
```
    • Wrong category of family instance; declaration was for a type family
    • In the data instance declaration for ‘Sing’
```
Maybe the `REAMDE` itself could show how to solve that?

**Comment by int-index** [comment]
`Sing` is a type family now. Instead of `data instance Sing (x :: Foo) = ...` you need to write

```
data SFoo (x :: Foo) = ...
type instance Sing = SFoo
```

**Comment by RyanGlScott** [comment]
For some additional context, there is currently [a section of the `README`](https://github.com/goldfirere/singletons/tree/01fa5635d8e4db0be8d9537a44d777541969354b#arrows-nat-symbol-and-literals) that explains uses this issue as the sole reference for how to implement this trick. Personally, I'm not quite happy with that, since I would prefer a more direct explanation of how to do this in the prose of the `README`, without having to read through the comments of a six-year-old GitHub issue. Moreover, as has just been demonstrated, the code involved in this trick is susceptible to bitrotting. Describing the trick in the `README` gives it a better chance of being maintained in the future, rather than languishing in obscurity here.

I'm going to reopen the issue to track the task of putting all of this into the `README`.

**Comment by RyanGlScott** [comment]
I've opened #451 for this. @nomeata, can you see if the new text that this PR adds to the `README` is to your liking?
