### ISSUE TITLE
Extended error reporting

### ISSUE THREAD

**Issue by lykahb** [goldfirere/singletons#89]
The error function tries to mimic the original one by accepting only Symbols. This significantly constrains error reporting because on the type level there is no show function and symbol manipulation.

I suggest to make its argument kind-polymorphic so that we can pass details on the error site.

**Comment by RyanGlScott** [comment]
@amesgen, that is a very good observation. Indeed, the type `Error (FromString "bad")` is ambiguous, as it is not clear which `PIsString` instance is supposed to be used. I think it is reasonable to expect `singletons [d|data Foo = Foo deriving (Enum)|]` to work even with `OverloadedStrings` enabled, so I think it is worth reopening this issue.

While this issue predates me becoming a co-maintainer of the library, I can't help but wonder if the original motivation still holds true. The original motivation from https://github.com/goldfirere/singletons/issues/89#issue-36182746 is:

> The error function tries to mimic the original one by accepting only Symbols. This significantly constrains error reporting because on the type level there is no show function and symbol manipulation.

Nowadays, there _is_ a type-level [`Show_`](https://hackage.haskell.org/package/singletons-base-3.1.1/docs/Data-Singletons-Base-TH.html#t:Show_) function, and the API for manipulating `Symbol`s is nearly as expressive as the API for manipulating `String`s. In light of this, I think a better design would be to:

* Give `Error` the kind `forall a. Symbol -> a`.
* Introduce a new `PolyError` type of kind `forall a b. a -> b` to replace the current, poly-kinded `Error` type.

Alternatively, we could keep `Error`'s current kind and introduce a separate `SymbolError :: forall a. Symbol -> a` type, which we could use in place of `Error` in derived `PEnum` instances. That being said, I'm not as fond of this approach, which the issue lies in the fact that `singletons-base` treats `Error` differently than it does `error`, and I feel like `Error` is the thing that ought to change.

Thoughts on this, @lykahb?

**Comment by RyanGlScott** [comment]
I've opened #554 with a patch that implements the `PolyError` plan.
