### ISSUE TITLE
Simpler library definitions = better deductions in user code

### ISSUE THREAD

**Issue by crockeea** [goldfirere/singletons#93]
Consider the class

    class StepList xs where
      step :: Proxy xs -> Head xs -> Last xs

    instance (StepList (x2 ': xs)) => StepList (x1 ': x2 ': xs) where
      step _ _ = step (Proxy::Proxy (x2 ': xs)) undefined

Using `Last` from Data.Singletons.Prelude results in the error `Could not deduce Last (x2 ': xs) ~ Last (x1 ': x2 ': xs)`

However, when I define either an open or closed type family for `Last`, i.e.

    type family Last (xs :: [k]) :: k
    type instance Last '[a] = a
    type instance Last (a ': a2 ': as) = Last (a2 ': as)

GHC is able to deduce this (obvious) constraint. Is there any way to get this deduction automatically with Singletons?

Aside: I expected I might have the same problem with `Head` from Singletons, namely that GHC would not be able to deduce `Head (x1 ': x2 ': xs) ~ Head (x1 ': xs)`, but apparently it can. I'm not sure why these seemingly-similar cases behave differently.

**Comment by goldfirere** [comment]
The problem is that the definition of `last` is not as simple as you think:

```
  last :: [a] -> a
  last []      =  error "Data.Singletons.List.last: empty list"
  last (x:xs)  =  last' x xs
    where last' :: a -> [a] -> a
          last' y []     = y
          last' _ (y:ys) = last' y ys
```

This is copied from the standard library definition. Of course, we don't *need* to copy the standard library here, and I think users would be better served by a simpler (but perhaps slightly less efficient) definition. We should take a pass through all the library definitions and simplify them if possible.

**Comment by goldfirere** [comment]
There may be other functions that could be simplified. If you want to simplify a function, please submit a PR (or at least make a specific request). Thanks!
