### ISSUE TITLE
Backwards state monad leads to cycle it type synonym declarations

### ISSUE THREAD

**Issue by jstolarek** [goldfirere/singletons#94]
The backwards state monad, which I proudly announced during the talk to be promotable, fails to promote with "Cycle in type synonym declarations". After some very painful bisecting (because of th-desugar dependency) it turns out that this was introduced by th-desugar switch in https://github.com/goldfirere/singletons/commit/be9c9cd56fdadc42760781515e6ab2764a83bdee

**Comment by goldfirere** [comment]
Now it just loops. But getting this to work out means that we need to have a real semantics for type family reduction, which GHC doesn't have. Until GHC catches up, this is a non-starter. But I'm not even going to label this as blocked upstream, because there's no plans to give GHC a well-defined semantics for type families in the near future. So I'm just closing this ticket as invalid, as we're trying to do something that GHC fundamentally doesn't support.

**Comment by jstolarek** [comment]
But remember that this *used to* work.

**Comment by goldfirere** [comment]
Yes, but I think that was as much of an accident as this is. And note that it worked on 7.8, so it's possible that my updates would make it work on 7.8 (if it compiled at all). There's a pretty big change in the way that type families reduce between 7.8 and 7.10.

**Comment by jstolarek** [comment]
> There's a pretty big change in the way that type families reduce between 7.8 and 7.10.

Where can I read more about this? Is there a ticket or a wiki page?

**Comment by goldfirere** [comment]
No. It was all meant to be under-the-hood. But it's quite conceivable that this sort of weirdness would change in behavior. It was done while fixing up how `Coercible` is solved.
